// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ordersql

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Fee struct {
	ID        uuid.UUID
	Name      string
	FeeType   string
	Value     decimal.Decimal
	Position  int32
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
