// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ordersql

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Attendee struct {
	ID           uuid.UUID
	OrderID      uuid.UUID
	TicketTypeID uuid.UUID
	Name         string
	Email        string
}

type Order struct {
	ID              uuid.UUID
	OrderNumber     string
	BuyerName       string
	BuyerEmail      string
	BuyerPhone      string
	TotalAmount     decimal.Decimal
	Status          string
	PaymentProvider *string
	PaymentUrl      *string
	EmailSent       *bool
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
}

type OrderItem struct {
	ID           uuid.UUID
	OrderID      uuid.UUID
	TicketTypeID uuid.UUID
	Quantity     int32
	Price        decimal.Decimal
}
