// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ordersql

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Fee struct {
	ID        uuid.UUID
	Name      string
	FeeType   string
	Value     decimal.Decimal
	Position  int32
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Order struct {
	ID               uuid.UUID
	OrderNumber      string
	BuyerName        *string
	BuyerEmail       *string
	BuyerPhone       *string
	TotalAmount      decimal.Decimal
	Status           string
	PaymentProvider  *string
	PaymentUrl       *string
	EmailSent        *bool
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	PaymentQrString  *string
	PaymentExpiresAt *time.Time
	TermsAgreedAt    *time.Time
	EventTermsID     uuid.NullUUID
	BuyerDob         pgtype.Date
	BuyerGender      *string
	Subtotal         decimal.NullDecimal
}
