// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package ordersql

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createAttendee = `-- name: CreateAttendee :one
INSERT INTO attendees (order_id, ticket_type_id, name, email)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, ticket_type_id, name, email
`

type CreateAttendeeParams struct {
	OrderID      uuid.UUID
	TicketTypeID uuid.UUID
	Name         string
	Email        string
}

func (q *Queries) CreateAttendee(ctx context.Context, arg CreateAttendeeParams) (Attendee, error) {
	row := q.db.QueryRow(ctx, createAttendee,
		arg.OrderID,
		arg.TicketTypeID,
		arg.Name,
		arg.Email,
	)
	var i Attendee
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TicketTypeID,
		&i.Name,
		&i.Email,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (order_number, buyer_name, buyer_email, buyer_phone, total_amount, status)
VALUES ($1, $2, $3, $4, $5, 'PENDING')
RETURNING id, order_number, buyer_name, buyer_email, buyer_phone, total_amount, status,
          payment_provider, payment_url, email_sent, created_at, updated_at
`

type CreateOrderParams struct {
	OrderNumber string
	BuyerName   string
	BuyerEmail  string
	BuyerPhone  string
	TotalAmount decimal.Decimal
}

// Checkout writes (TX1) ----------------------------------------------------
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNumber,
		arg.BuyerName,
		arg.BuyerEmail,
		arg.BuyerPhone,
		arg.TotalAmount,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentProvider,
		&i.PaymentUrl,
		&i.EmailSent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, ticket_type_id, quantity, price)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, ticket_type_id, quantity, price
`

type CreateOrderItemParams struct {
	OrderID      uuid.UUID
	TicketTypeID uuid.UUID
	Quantity     int32
	Price        decimal.Decimal
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.TicketTypeID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one

SELECT id, order_number, buyer_name, buyer_email, buyer_phone, total_amount, status,
       payment_provider, payment_url, email_sent, created_at, updated_at
FROM orders
WHERE id = $1
`

// Reads --------------------------------------------------------------------
func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentProvider,
		&i.PaymentUrl,
		&i.EmailSent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, order_number, buyer_name, buyer_email, buyer_phone, total_amount, status,
       payment_provider, payment_url, email_sent, created_at, updated_at
FROM orders
WHERE order_number = $1
`

func (q *Queries) GetOrderByNumber(ctx context.Context, orderNumber string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByNumber, orderNumber)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentProvider,
		&i.PaymentUrl,
		&i.EmailSent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasOrdersForTicketType = `-- name: HasOrdersForTicketType :one

SELECT (
    EXISTS (SELECT 1 FROM order_items oi WHERE oi.ticket_type_id = $1)
    OR
    EXISTS (SELECT 1 FROM attendees a WHERE a.ticket_type_id = $1)
) AS has_orders
`

// OrderChecker (delete guards + derived sold counts) ------------------------
// Both FKs onto ticket_types are ON DELETE RESTRICT, so a guard that inspects only
// order_items would surface a raw constraint violation instead of the required 400
// (constitution, Principle VI).
func (q *Queries) HasOrdersForTicketType(ctx context.Context, ticketTypeID uuid.UUID) (*bool, error) {
	row := q.db.QueryRow(ctx, hasOrdersForTicketType, ticketTypeID)
	var has_orders *bool
	err := row.Scan(&has_orders)
	return has_orders, err
}

const hasOrdersForTicketTypes = `-- name: HasOrdersForTicketTypes :one
SELECT (
    EXISTS (SELECT 1 FROM order_items oi WHERE oi.ticket_type_id = ANY($1::uuid[]))
    OR
    EXISTS (SELECT 1 FROM attendees a WHERE a.ticket_type_id = ANY($1::uuid[]))
) AS has_orders
`

func (q *Queries) HasOrdersForTicketTypes(ctx context.Context, ids []uuid.UUID) (*bool, error) {
	row := q.db.QueryRow(ctx, hasOrdersForTicketTypes, ids)
	var has_orders *bool
	err := row.Scan(&has_orders)
	return has_orders, err
}

const listAttendeesAdmin = `-- name: ListAttendeesAdmin :many
SELECT a.id, a.order_id, a.ticket_type_id, a.name, a.email, o.order_number
FROM attendees a
JOIN orders o ON o.id = a.order_id
WHERE ($1::uuid IS NULL OR a.order_id = $1::uuid)
  AND (
        $2::uuid[] IS NULL
        OR a.ticket_type_id = ANY($2::uuid[])
      )
ORDER BY o.created_at DESC, a.name ASC
`

type ListAttendeesAdminParams struct {
	OrderID       uuid.NullUUID
	TicketTypeIds []uuid.UUID
}

type ListAttendeesAdminRow struct {
	ID           uuid.UUID
	OrderID      uuid.UUID
	TicketTypeID uuid.UUID
	Name         string
	Email        string
	OrderNumber  string
}

func (q *Queries) ListAttendeesAdmin(ctx context.Context, arg ListAttendeesAdminParams) ([]ListAttendeesAdminRow, error) {
	rows, err := q.db.Query(ctx, listAttendeesAdmin, arg.OrderID, arg.TicketTypeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendeesAdminRow{}
	for rows.Next() {
		var i ListAttendeesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TicketTypeID,
			&i.Name,
			&i.Email,
			&i.OrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendeesByOrderID = `-- name: ListAttendeesByOrderID :many
SELECT id, order_id, ticket_type_id, name, email
FROM attendees
WHERE order_id = $1
ORDER BY id ASC
`

func (q *Queries) ListAttendeesByOrderID(ctx context.Context, orderID uuid.UUID) ([]Attendee, error) {
	rows, err := q.db.Query(ctx, listAttendeesByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attendee{}
	for rows.Next() {
		var i Attendee
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TicketTypeID,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, ticket_type_id, quantity, price
FROM order_items
WHERE order_id = $1
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersAdmin = `-- name: ListOrdersAdmin :many

SELECT id, order_number, buyer_name, buyer_email, buyer_phone, total_amount, status,
       payment_provider, payment_url, email_sent, created_at, updated_at
FROM orders
WHERE ($1::text IS NULL OR status = $1::text)
  AND (
        $2::uuid[] IS NULL
        OR EXISTS (
            SELECT 1 FROM order_items oi
            WHERE oi.order_id = orders.id
              AND oi.ticket_type_id = ANY($2::uuid[])
        )
      )
ORDER BY created_at DESC
`

type ListOrdersAdminParams struct {
	Status        *string
	TicketTypeIds []uuid.UUID
}

// Admin read-only views ----------------------------------------------------
func (q *Queries) ListOrdersAdmin(ctx context.Context, arg ListOrdersAdminParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersAdmin, arg.Status, arg.TicketTypeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.BuyerName,
			&i.BuyerEmail,
			&i.BuyerPhone,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentProvider,
			&i.PaymentUrl,
			&i.EmailSent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderNumberExists = `-- name: OrderNumberExists :one
SELECT EXISTS (SELECT 1 FROM orders WHERE order_number = $1) AS taken
`

func (q *Queries) OrderNumberExists(ctx context.Context, orderNumber string) (bool, error) {
	row := q.db.QueryRow(ctx, orderNumberExists, orderNumber)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const setEmailSent = `-- name: SetEmailSent :execrows
UPDATE orders SET email_sent = TRUE, updated_at = now() WHERE id = $1
`

func (q *Queries) SetEmailSent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, setEmailSent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const soldCountByTicketTypes = `-- name: SoldCountByTicketTypes :many
SELECT ticket_type_id, SUM(quantity)::bigint AS sold
FROM order_items
WHERE ticket_type_id = ANY($1::uuid[])
GROUP BY ticket_type_id
`

type SoldCountByTicketTypesRow struct {
	TicketTypeID uuid.UUID
	Sold         int64
}

// Derived, never stored (constitution, Critical Data Flow Rules). Batched over a
// whole page of ticket types so admin listings issue one query, not N.
func (q *Queries) SoldCountByTicketTypes(ctx context.Context, ids []uuid.UUID) ([]SoldCountByTicketTypesRow, error) {
	rows, err := q.db.Query(ctx, soldCountByTicketTypes, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SoldCountByTicketTypesRow{}
	for rows.Next() {
		var i SoldCountByTicketTypesRow
		if err := rows.Scan(&i.TicketTypeID, &i.Sold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatusIfPending = `-- name: UpdateOrderStatusIfPending :execrows
UPDATE orders
SET status = $2, updated_at = now()
WHERE id = $1 AND status = 'PENDING'
`

type UpdateOrderStatusIfPendingParams struct {
	ID     uuid.UUID
	Status string
}

// Guarded on PENDING so a replayed webhook notification cannot apply the same
// transition (and its quota restoration) twice.
func (q *Queries) UpdateOrderStatusIfPending(ctx context.Context, arg UpdateOrderStatusIfPendingParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatusIfPending, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePaymentDetails = `-- name: UpdatePaymentDetails :execrows

UPDATE orders
SET payment_url = $2, payment_provider = $3, updated_at = now()
WHERE id = $1
`

type UpdatePaymentDetailsParams struct {
	ID              uuid.UUID
	PaymentUrl      *string
	PaymentProvider *string
}

// Payment lifecycle --------------------------------------------------------
func (q *Queries) UpdatePaymentDetails(ctx context.Context, arg UpdatePaymentDetailsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePaymentDetails, arg.ID, arg.PaymentUrl, arg.PaymentProvider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
