// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package ordersql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countAttendeesAdmin = `-- name: CountAttendeesAdmin :one
SELECT count(*)
FROM attendees a
JOIN orders o ON o.id = a.order_id
WHERE ($1::uuid IS NULL OR a.order_id = $1::uuid)
  AND (
        $2::uuid[] IS NULL
        OR a.ticket_type_id = ANY($2::uuid[])
      )
  AND (
        $3::text IS NULL
        OR a.name         ILIKE '%' || $3::text || '%'
        OR a.email        ILIKE '%' || $3::text || '%'
        OR o.order_number ILIKE '%' || $3::text || '%'
      )
`

type CountAttendeesAdminParams struct {
	OrderID       uuid.NullUUID
	TicketTypeIds []uuid.UUID
	Search        *string
}

// Pairs with ListAttendeesAdmin below. Keep the two WHERE clauses identical.
func (q *Queries) CountAttendeesAdmin(ctx context.Context, arg CountAttendeesAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttendeesAdmin, arg.OrderID, arg.TicketTypeIds, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFees = `-- name: CountFees :one
SELECT count(*) FROM fees
`

// Pairs with ListFees below.
func (q *Queries) CountFees(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFees)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersAdmin = `-- name: CountOrdersAdmin :one


SELECT count(*)
FROM orders o
JOIN order_statuses os ON os.id = o.status_id
WHERE ($1::text IS NULL OR os.name = $1::text)
  AND (
        $2::uuid[] IS NULL
        OR EXISTS (
            SELECT 1 FROM order_items oi
            WHERE oi.order_id = o.id
              AND oi.ticket_type_id = ANY($2::uuid[])
        )
      )
  AND (
        $3::text IS NULL
        OR o.order_number ILIKE '%' || $3::text || '%'
        OR o.buyer_name   ILIKE '%' || $3::text || '%'
        OR o.buyer_email  ILIKE '%' || $3::text || '%'
      )
`

type CountOrdersAdminParams struct {
	Status        *string
	TicketTypeIds []uuid.UUID
	Search        *string
}

// Admin read-only views ----------------------------------------------------
// Spec 021: the admin lists are paginated. Each list read is a PAIR — a count
// and a page — and the pair MUST share one WHERE clause verbatim. The count runs
// first because clamping an out-of-range page to the last one needs the total
// before the slice is taken, and a page read past the end comes back empty with
// nothing to clamp against (spec 021 research R3).
//
// Every ORDER BY here ends in a primary key. That is not decoration: without a
// total order, PostgreSQL may return rows tied on the leading key in different
// relative orders for two different OFFSETs, which shows an operator a duplicate
// on page 2 while hiding a different record entirely (spec 021 research R4).
// Pairs with ListOrdersAdmin below. Keep the two WHERE clauses identical.
func (q *Queries) CountOrdersAdmin(ctx context.Context, arg CountOrdersAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersAdmin, arg.Status, arg.TicketTypeIds, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttendeeSlot = `-- name: CreateAttendeeSlot :one

INSERT INTO attendees (order_id, ticket_type_id, package_id, package_unit)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, ticket_type_id, package_id, package_unit, name, email, phone, dob, gender_id
`

type CreateAttendeeSlotParams struct {
	OrderID      uuid.UUID
	TicketTypeID uuid.UUID
	PackageID    uuid.NullUUID
	PackageUnit  *int16
}

type CreateAttendeeSlotRow struct {
	ID           uuid.UUID
	OrderID      uuid.UUID
	TicketTypeID uuid.UUID
	PackageID    uuid.NullUUID
	PackageUnit  *int16
	Name         *string
	Email        *string
	Phone        *string
	Dob          pgtype.Date
	GenderID     *int16
}

// Spec 022 FR-023: there is deliberately NO per-address query here.
//
// An earlier draft carried EmailHasIssuedTicketForEvent (does this address
// already hold a place at this event?) and LockRegistrationIdentity (an advisory
// xact lock keyed on event+lower(email), taken first so the check above was not
// a read-then-write race). Both are gone: the rule they enforced was removed,
// and an address may now register as many times as remaining quota allows.
//
// Nothing in the registration write path may be keyed on the email address
// (FR-023a). Two submissions of one address must not contend, which is why the
// lock went with the check rather than being kept "just in case" — a lock with
// no invariant to protect is pure serialisation of the hot path.
// An EMPTY slot: ticket-type-bound at booking, identity filled at checkout.
// package_unit ties bundle slots to their purchased unit (spec 010).
func (q *Queries) CreateAttendeeSlot(ctx context.Context, arg CreateAttendeeSlotParams) (CreateAttendeeSlotRow, error) {
	row := q.db.QueryRow(ctx, createAttendeeSlot,
		arg.OrderID,
		arg.TicketTypeID,
		arg.PackageID,
		arg.PackageUnit,
	)
	var i CreateAttendeeSlotRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TicketTypeID,
		&i.PackageID,
		&i.PackageUnit,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Dob,
		&i.GenderID,
	)
	return i, err
}

const createBookedOrder = `-- name: CreateBookedOrder :one

WITH inserted AS (
    INSERT INTO orders (order_number, total_amount, subtotal, status_id, payment_expires_at)
    VALUES ($1, $2, $3, (SELECT ost.id FROM order_statuses ost WHERE ost.name = 'PENDING'), $4)
    RETURNING id, order_number, buyer_name, buyer_email, buyer_phone, total_amount,
              status_id, payment_provider, payment_url, email_sent, created_at,
              updated_at, payment_qr_string, payment_expires_at, terms_agreed_at,
              event_terms_id, subtotal
)
SELECT i.id, i.order_number, i.buyer_name, i.buyer_email, i.buyer_phone, i.total_amount,
       os.name AS status,
       i.payment_provider, i.payment_url, i.email_sent, i.created_at, i.updated_at,
       i.payment_qr_string, i.payment_expires_at, i.terms_agreed_at, i.event_terms_id,
       i.subtotal,
       EXISTS (
           SELECT 1 FROM order_items oi
           JOIN ticket_types tt ON tt.id = oi.ticket_type_id
           WHERE oi.order_id = i.id AND NOT tt.is_visible
       ) AS is_registration
FROM inserted i
JOIN order_statuses os ON os.id = i.status_id
`

type CreateBookedOrderParams struct {
	OrderNumber      string
	TotalAmount      decimal.Decimal
	Subtotal         decimal.NullDecimal
	PaymentExpiresAt *time.Time
}

type CreateBookedOrderRow struct {
	ID               uuid.UUID
	OrderNumber      string
	BuyerName        *string
	BuyerEmail       *string
	BuyerPhone       *string
	TotalAmount      decimal.Decimal
	Status           string
	PaymentProvider  *string
	PaymentUrl       *string
	EmailSent        *bool
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	PaymentQrString  *string
	PaymentExpiresAt *time.Time
	TermsAgreedAt    *time.Time
	EventTermsID     uuid.NullUUID
	Subtotal         decimal.NullDecimal
	IsRegistration   bool
}

// Spec 008: two-phase booking ------------------------------------------------
// Booking (TX-B): the order exists before any contact identity — those columns
// stay NULL until checkout. payment_expires_at carries the 1-hour hold.
//
// Wrapped in a CTE because RETURNING cannot join: the insert resolves PENDING to
// its id, then the outer select joins the master list back so the caller still
// receives `status` as the NAME, with the same NOT NULL string type as every
// other order read (research R19).
func (q *Queries) CreateBookedOrder(ctx context.Context, arg CreateBookedOrderParams) (CreateBookedOrderRow, error) {
	row := q.db.QueryRow(ctx, createBookedOrder,
		arg.OrderNumber,
		arg.TotalAmount,
		arg.Subtotal,
		arg.PaymentExpiresAt,
	)
	var i CreateBookedOrderRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentProvider,
		&i.PaymentUrl,
		&i.EmailSent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentQrString,
		&i.PaymentExpiresAt,
		&i.TermsAgreedAt,
		&i.EventTermsID,
		&i.Subtotal,
		&i.IsRegistration,
	)
	return i, err
}

const createFee = `-- name: CreateFee :one
INSERT INTO fees (name, fee_type, value, position, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, fee_type, value, position, is_active, created_at, updated_at
`

type CreateFeeParams struct {
	Name     string
	FeeType  string
	Value    decimal.Decimal
	Position int32
	IsActive bool
}

func (q *Queries) CreateFee(ctx context.Context, arg CreateFeeParams) (Fee, error) {
	row := q.db.QueryRow(ctx, createFee,
		arg.Name,
		arg.FeeType,
		arg.Value,
		arg.Position,
		arg.IsActive,
	)
	var i Fee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FeeType,
		&i.Value,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderFee = `-- name: CreateOrderFee :exec
INSERT INTO order_fees (order_id, name, amount, position)
VALUES ($1, $2, $3, $4)
`

type CreateOrderFeeParams struct {
	OrderID  uuid.UUID
	Name     string
	Amount   decimal.Decimal
	Position int32
}

// Booking (TX-B): freezes one computed fee line onto the order.
func (q *Queries) CreateOrderFee(ctx context.Context, arg CreateOrderFeeParams) error {
	_, err := q.db.Exec(ctx, createOrderFee,
		arg.OrderID,
		arg.Name,
		arg.Amount,
		arg.Position,
	)
	return err
}

const createOrderItem = `-- name: CreateOrderItem :one

INSERT INTO order_items (order_id, ticket_type_id, package_id, quantity, price)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, ticket_type_id, package_id, quantity, price
`

type CreateOrderItemParams struct {
	OrderID      uuid.UUID
	TicketTypeID uuid.NullUUID
	PackageID    uuid.NullUUID
	Quantity     int32
	Price        decimal.Decimal
}

type CreateOrderItemRow struct {
	ID           uuid.UUID
	OrderID      uuid.UUID
	TicketTypeID uuid.NullUUID
	PackageID    uuid.NullUUID
	Quantity     int32
	Price        decimal.Decimal
}

// Checkout writes (TX1) ----------------------------------------------------
// Exactly one of ticket_type_id / package_id is set (order_items_line_kind_chk). A
// package line is stored ONCE at the package's own price rather than expanded into
// per-constituent rows, so total_amount stays exactly SUM(quantity * price).
func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (CreateOrderItemRow, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.TicketTypeID,
		arg.PackageID,
		arg.Quantity,
		arg.Price,
	)
	var i CreateOrderItemRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TicketTypeID,
		&i.PackageID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const createRegistrationOrder = `-- name: CreateRegistrationOrder :one
WITH inserted AS (
    INSERT INTO orders (order_number, total_amount, subtotal, status_id,
                        buyer_name, buyer_email, buyer_phone,
                        terms_agreed_at, event_terms_id)
    VALUES ($1, 0, 0, (SELECT ost.id FROM order_statuses ost WHERE ost.name = 'PAID'),
            $2, $3, $4, now(), $5)
    RETURNING id, order_number, buyer_name, buyer_email, buyer_phone, total_amount,
              status_id, payment_provider, payment_url, email_sent, created_at,
              updated_at, payment_qr_string, payment_expires_at, terms_agreed_at,
              event_terms_id, subtotal
)
SELECT i.id, i.order_number, i.buyer_name, i.buyer_email, i.buyer_phone, i.total_amount,
       os.name AS status,
       i.payment_provider, i.payment_url, i.email_sent, i.created_at, i.updated_at,
       i.payment_qr_string, i.payment_expires_at, i.terms_agreed_at, i.event_terms_id,
       i.subtotal,
       EXISTS (
           SELECT 1 FROM order_items oi
           JOIN ticket_types tt ON tt.id = oi.ticket_type_id
           WHERE oi.order_id = i.id AND NOT tt.is_visible
       ) AS is_registration
FROM inserted i
JOIN order_statuses os ON os.id = i.status_id
`

type CreateRegistrationOrderParams struct {
	OrderNumber  string
	BuyerName    *string
	BuyerEmail   *string
	BuyerPhone   *string
	EventTermsID uuid.NullUUID
}

type CreateRegistrationOrderRow struct {
	ID               uuid.UUID
	OrderNumber      string
	BuyerName        *string
	BuyerEmail       *string
	BuyerPhone       *string
	TotalAmount      decimal.Decimal
	Status           string
	PaymentProvider  *string
	PaymentUrl       *string
	EmailSent        *bool
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	PaymentQrString  *string
	PaymentExpiresAt *time.Time
	TermsAgreedAt    *time.Time
	EventTermsID     uuid.NullUUID
	Subtotal         decimal.NullDecimal
	IsRegistration   bool
}

// Spec 022: the free-registration order. Created FINAL — PAID, zero total — in one
// statement.
//
// NOTHING marks it as a registration. The distinction is DERIVED from the ticket
// type its single line references (decision reversed 2026-08-20), so
// `is_registration` in the row this returns is necessarily FALSE: the line is
// inserted after this statement, so at this instant the order has no items to
// derive from. No caller reads it from here — the delivery path re-reads through
// GetOrderByID once the line exists — and it is returned only because the Go layer
// casts this row to GetOrderByIDRow and the two column lists must match.
//
// Everything is inline BECAUSE IT HAS TO BE. The two obvious "insert then patch"
// queries are both guarded on PENDING and would silently affect zero rows here:
// UpdateOrderBuyer and RecordTermsAgreement. Their repository wrappers map "0
// rows" to false, which the service reports as 410 ORDER_EXPIRED — so a
// registration that actually succeeded would be reported to the guest as gone.
//
// buyer_email in particular is load-bearing: notification.SendTicketEmail reads
// orders.buyer_email and refuses an empty snapshot outright, so a registration
// that left it NULL would issue a ticket and then silently fail to deliver it —
// after the guest has already been told it was sent (spec 022 FR-039e).
//
// payment_expires_at is left NULL, not set: it is what every order read renders a
// live countdown from, and what the expiry sweeper's partial index selects on.
// A registration is already final and must never look payable or be swept.
//
// No order_fees rows accompany this insert and no payments row ever will
// (FR-027, FR-029). Constitution Principle IV v5.0.0 admits this as the one path
// to PAID without a gateway.
//
// Same CTE shape as CreateBookedOrder, and the same column list: the Go layer
// casts this row to GetOrderByIDRow, so the two must stay identical.
func (q *Queries) CreateRegistrationOrder(ctx context.Context, arg CreateRegistrationOrderParams) (CreateRegistrationOrderRow, error) {
	row := q.db.QueryRow(ctx, createRegistrationOrder,
		arg.OrderNumber,
		arg.BuyerName,
		arg.BuyerEmail,
		arg.BuyerPhone,
		arg.EventTermsID,
	)
	var i CreateRegistrationOrderRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentProvider,
		&i.PaymentUrl,
		&i.EmailSent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentQrString,
		&i.PaymentExpiresAt,
		&i.TermsAgreedAt,
		&i.EventTermsID,
		&i.Subtotal,
		&i.IsRegistration,
	)
	return i, err
}

const deleteFee = `-- name: DeleteFee :execrows
DELETE FROM fees WHERE id = $1
`

func (q *Queries) DeleteFee(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFee, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrderByID = `-- name: GetOrderByID :one

SELECT o.id, o.order_number, o.buyer_name, o.buyer_email, o.buyer_phone, o.total_amount,
       os.name AS status,
       o.payment_provider, o.payment_url, o.email_sent, o.created_at, o.updated_at,
       o.payment_qr_string, o.payment_expires_at, o.terms_agreed_at, o.event_terms_id,
       o.subtotal,
       EXISTS (
           SELECT 1 FROM order_items oi
           JOIN ticket_types tt ON tt.id = oi.ticket_type_id
           WHERE oi.order_id = o.id AND NOT tt.is_visible
       ) AS is_registration
FROM orders o
JOIN order_statuses os ON os.id = o.status_id
WHERE o.id = $1
`

type GetOrderByIDRow struct {
	ID               uuid.UUID
	OrderNumber      string
	BuyerName        *string
	BuyerEmail       *string
	BuyerPhone       *string
	TotalAmount      decimal.Decimal
	Status           string
	PaymentProvider  *string
	PaymentUrl       *string
	EmailSent        *bool
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	PaymentQrString  *string
	PaymentExpiresAt *time.Time
	TermsAgreedAt    *time.Time
	EventTermsID     uuid.NullUUID
	Subtotal         decimal.NullDecimal
	IsRegistration   bool
}

// Reads --------------------------------------------------------------------
// The trailing two columns are listed in migration order (0002 appended them
// after updated_at), which is what lets sqlc reuse the single Order struct
// instead of emitting a near-identical row type per query.
// Every order read joins the status master list and aliases the NAME back to
// `status`, so the generated Order struct still carries `Status string` holding
// PENDING/PAID/CANCELLED/EXPIRED. That is the whole reason migration 0013 costs
// no Go changes (research R19) — keep the alias if you touch these.
//
// `is_registration` is DERIVED, not stored (spec 022, decision reversed
// 2026-08-20). An order is a registration when it carries a line for a
// registration-only ticket type — containment guarantees such a type can never be
// bought or bundled, so one such line can only have come from the registration
// path.
//
// The JOIN reaches into the event domain's table. Principle II permits that on a
// READ; the registration WRITE still reaches quota only through EventProvider.
//
// KNOWN AND ACCEPTED CONSEQUENCE: this value is not stable over time. An admin who
// makes an invitation ticket type purchasable again retroactively reclassifies
// every order that used it, and a resend of an old registration would then render
// a receipt for an order that never had a payment. That was raised and the
// derivation was chosen deliberately over a stored marker.
func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentProvider,
		&i.PaymentUrl,
		&i.EmailSent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentQrString,
		&i.PaymentExpiresAt,
		&i.TermsAgreedAt,
		&i.EventTermsID,
		&i.Subtotal,
		&i.IsRegistration,
	)
	return i, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT o.id, o.order_number, o.buyer_name, o.buyer_email, o.buyer_phone, o.total_amount,
       os.name AS status,
       o.payment_provider, o.payment_url, o.email_sent, o.created_at, o.updated_at,
       o.payment_qr_string, o.payment_expires_at, o.terms_agreed_at, o.event_terms_id,
       o.subtotal,
       EXISTS (
           SELECT 1 FROM order_items oi
           JOIN ticket_types tt ON tt.id = oi.ticket_type_id
           WHERE oi.order_id = o.id AND NOT tt.is_visible
       ) AS is_registration
FROM orders o
JOIN order_statuses os ON os.id = o.status_id
WHERE o.order_number = $1
`

type GetOrderByNumberRow struct {
	ID               uuid.UUID
	OrderNumber      string
	BuyerName        *string
	BuyerEmail       *string
	BuyerPhone       *string
	TotalAmount      decimal.Decimal
	Status           string
	PaymentProvider  *string
	PaymentUrl       *string
	EmailSent        *bool
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	PaymentQrString  *string
	PaymentExpiresAt *time.Time
	TermsAgreedAt    *time.Time
	EventTermsID     uuid.NullUUID
	Subtotal         decimal.NullDecimal
	IsRegistration   bool
}

func (q *Queries) GetOrderByNumber(ctx context.Context, orderNumber string) (GetOrderByNumberRow, error) {
	row := q.db.QueryRow(ctx, getOrderByNumber, orderNumber)
	var i GetOrderByNumberRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentProvider,
		&i.PaymentUrl,
		&i.EmailSent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentQrString,
		&i.PaymentExpiresAt,
		&i.TermsAgreedAt,
		&i.EventTermsID,
		&i.Subtotal,
		&i.IsRegistration,
	)
	return i, err
}

const getOrderEventID = `-- name: GetOrderEventID :one
SELECT tt.event_id
FROM attendees a
JOIN ticket_types tt ON tt.id = a.ticket_type_id
WHERE a.order_id = $1
LIMIT 1
`

// The event an order belongs to, resolved through its attendee slots (every
// booked order has at least one, and each slot binds a concrete ticket type).
func (q *Queries) GetOrderEventID(ctx context.Context, orderID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getOrderEventID, orderID)
	var event_id uuid.UUID
	err := row.Scan(&event_id)
	return event_id, err
}

const getOrderWithTermsByNumber = `-- name: GetOrderWithTermsByNumber :one
SELECT o.id, o.order_number, o.buyer_name, o.buyer_email, o.buyer_phone, o.total_amount,
       os.name AS status,
       o.payment_provider, o.payment_url, o.email_sent, o.created_at, o.updated_at,
       o.payment_qr_string, o.payment_expires_at, o.terms_agreed_at, o.event_terms_id,
       o.subtotal
FROM orders o
JOIN order_statuses os ON os.id = o.status_id
WHERE o.order_number = $1
`

type GetOrderWithTermsByNumberRow struct {
	ID               uuid.UUID
	OrderNumber      string
	BuyerName        *string
	BuyerEmail       *string
	BuyerPhone       *string
	TotalAmount      decimal.Decimal
	Status           string
	PaymentProvider  *string
	PaymentUrl       *string
	EmailSent        *bool
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	PaymentQrString  *string
	PaymentExpiresAt *time.Time
	TermsAgreedAt    *time.Time
	EventTermsID     uuid.NullUUID
	Subtotal         decimal.NullDecimal
}

// The 008 guest read: everything the order page needs to pick its screen. The
// screen it picks is chosen from the status NAME, which the join preserves.
func (q *Queries) GetOrderWithTermsByNumber(ctx context.Context, orderNumber string) (GetOrderWithTermsByNumberRow, error) {
	row := q.db.QueryRow(ctx, getOrderWithTermsByNumber, orderNumber)
	var i GetOrderWithTermsByNumberRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentProvider,
		&i.PaymentUrl,
		&i.EmailSent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentQrString,
		&i.PaymentExpiresAt,
		&i.TermsAgreedAt,
		&i.EventTermsID,
		&i.Subtotal,
	)
	return i, err
}

const hasOrdersForPackage = `-- name: HasOrdersForPackage :one
SELECT (
    EXISTS (SELECT 1 FROM order_items oi WHERE oi.package_id = $1)
    OR
    EXISTS (SELECT 1 FROM attendees a WHERE a.package_id = $1)
) AS has_orders
`

// Delete guard for a package. Both FKs are ON DELETE RESTRICT, so this must return
// a clean 400 rather than letting a raw constraint violation surface.
func (q *Queries) HasOrdersForPackage(ctx context.Context, packageID uuid.NullUUID) (*bool, error) {
	row := q.db.QueryRow(ctx, hasOrdersForPackage, packageID)
	var has_orders *bool
	err := row.Scan(&has_orders)
	return has_orders, err
}

const hasOrdersForTicketType = `-- name: HasOrdersForTicketType :one

SELECT (
    EXISTS (SELECT 1 FROM order_items oi WHERE oi.ticket_type_id = $1)
    OR
    EXISTS (SELECT 1 FROM attendees a WHERE a.ticket_type_id = $1)
) AS has_orders
`

// OrderChecker (delete guards + derived sold counts) ------------------------
// Both FKs onto ticket_types are ON DELETE RESTRICT, so a guard that inspects only
// order_items would surface a raw constraint violation instead of the required 400
// (constitution, Principle VI).
func (q *Queries) HasOrdersForTicketType(ctx context.Context, ticketTypeID uuid.NullUUID) (*bool, error) {
	row := q.db.QueryRow(ctx, hasOrdersForTicketType, ticketTypeID)
	var has_orders *bool
	err := row.Scan(&has_orders)
	return has_orders, err
}

const hasOrdersForTicketTypes = `-- name: HasOrdersForTicketTypes :one
SELECT (
    EXISTS (SELECT 1 FROM order_items oi WHERE oi.ticket_type_id = ANY($1::uuid[]))
    OR
    EXISTS (SELECT 1 FROM attendees a WHERE a.ticket_type_id = ANY($1::uuid[]))
) AS has_orders
`

func (q *Queries) HasOrdersForTicketTypes(ctx context.Context, ids []uuid.UUID) (*bool, error) {
	row := q.db.QueryRow(ctx, hasOrdersForTicketTypes, ids)
	var has_orders *bool
	err := row.Scan(&has_orders)
	return has_orders, err
}

const hasPendingOrdersForPackage = `-- name: HasPendingOrdersForPackage :one
SELECT EXISTS (
    SELECT 1 FROM order_items oi
    JOIN orders o ON o.id = oi.order_id
    WHERE oi.package_id = $1
      AND o.status_id = (SELECT ost.id FROM order_statuses ost WHERE ost.name = 'PENDING')
) AS has_pending
`

// Composition-lock guard (research.md R-004): an open PENDING order holding this
// package means its composition cannot change, or restoration after expiry would
// put back a different amount than was deducted. PAID or terminal orders are not
// a constraint — their hold is permanent.
func (q *Queries) HasPendingOrdersForPackage(ctx context.Context, packageID uuid.NullUUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingOrdersForPackage, packageID)
	var has_pending bool
	err := row.Scan(&has_pending)
	return has_pending, err
}

const listActiveFees = `-- name: ListActiveFees :many

SELECT id, name, fee_type, value, position
FROM fees
WHERE is_active
ORDER BY position, name
`

type ListActiveFeesRow struct {
	ID       uuid.UUID
	Name     string
	FeeType  string
	Value    decimal.Decimal
	Position int32
}

// Fees (master + per-order snapshot; clarified 2026-08-05) -------------------
// The fee master rows booking applies, in display order.
func (q *Queries) ListActiveFees(ctx context.Context) ([]ListActiveFeesRow, error) {
	rows, err := q.db.Query(ctx, listActiveFees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveFeesRow{}
	for rows.Next() {
		var i ListActiveFeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FeeType,
			&i.Value,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveGenders = `-- name: ListActiveGenders :many
SELECT id, name FROM genders WHERE is_active ORDER BY name
`

type ListActiveGendersRow struct {
	ID   int16
	Name string
}

// The gender master list as the FORMS' OPTIONS (clarified 2026-08-05): active
// entries only, and it must stay that way. Spec 011 FR-031 widens one card's
// option list to show a gender that card already holds; it does not widen this.
func (q *Queries) ListActiveGenders(ctx context.Context) ([]ListActiveGendersRow, error) {
	rows, err := q.db.Query(ctx, listActiveGenders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveGendersRow{}
	for rows.Next() {
		var i ListActiveGendersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendeeSlotsByOrderID = `-- name: ListAttendeeSlotsByOrderID :many
SELECT a.id, a.order_id, a.ticket_type_id, a.package_id, a.package_unit,
       a.name, a.email, a.phone, a.dob, a.gender_id, g.name AS gender,
       tt.name AS ticket_type_name
FROM attendees a
JOIN ticket_types tt ON tt.id = a.ticket_type_id
LEFT JOIN genders g ON g.id = a.gender_id
WHERE a.order_id = $1
ORDER BY a.package_id NULLS FIRST, a.package_unit ASC, a.id ASC
`

type ListAttendeeSlotsByOrderIDRow struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	TicketTypeID   uuid.UUID
	PackageID      uuid.NullUUID
	PackageUnit    *int16
	Name           *string
	Email          *string
	Phone          *string
	Dob            pgtype.Date
	GenderID       *int16
	Gender         *string
	TicketTypeName string
}

// Slot list incl. the 008 detail columns and the human ticket-type name.
// Ordering (spec 010): standalone slots first, then bundle slots contiguous
// per (package_id, package_unit), so one visitor form maps to one unit. The
// FIRST row of this ordering is the order's primary contact (spec 011).
// gender comes back as BOTH the master row's id and its NAME (spec 011 FR-035,
// clarified 2026-08-24). Not redundancy: a form submits the id, a guest is shown
// the name, and a RETIRED entry is absent from the active master list — so a
// client given only one of the two could not resolve the other, and FR-031's
// restored form would break in one direction or the other. LEFT JOIN: an
// unfilled slot is NULL in both.
func (q *Queries) ListAttendeeSlotsByOrderID(ctx context.Context, orderID uuid.UUID) ([]ListAttendeeSlotsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listAttendeeSlotsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendeeSlotsByOrderIDRow{}
	for rows.Next() {
		var i ListAttendeeSlotsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TicketTypeID,
			&i.PackageID,
			&i.PackageUnit,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Dob,
			&i.GenderID,
			&i.Gender,
			&i.TicketTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendeesAdmin = `-- name: ListAttendeesAdmin :many
SELECT a.id, a.order_id, a.ticket_type_id, a.name, a.email, o.order_number,
       EXISTS (
           SELECT 1 FROM order_items oi
           JOIN ticket_types tt ON tt.id = oi.ticket_type_id
           WHERE oi.order_id = o.id AND NOT tt.is_visible
       ) AS is_registration
FROM attendees a
JOIN orders o ON o.id = a.order_id
WHERE ($1::uuid IS NULL OR a.order_id = $1::uuid)
  AND (
        $2::uuid[] IS NULL
        OR a.ticket_type_id = ANY($2::uuid[])
      )
  AND (
        $3::text IS NULL
        OR a.name         ILIKE '%' || $3::text || '%'
        OR a.email        ILIKE '%' || $3::text || '%'
        OR o.order_number ILIKE '%' || $3::text || '%'
      )
ORDER BY o.created_at DESC, a.name ASC, a.id ASC
LIMIT $5::int OFFSET $4::int
`

type ListAttendeesAdminParams struct {
	OrderID       uuid.NullUUID
	TicketTypeIds []uuid.UUID
	Search        *string
	RowOffset     int32
	RowLimit      int32
}

type ListAttendeesAdminRow struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	TicketTypeID   uuid.UUID
	Name           *string
	Email          *string
	OrderNumber    string
	IsRegistration bool
}

// a.id breaks the tie that `created_at, name` leaves open constantly: one
// order's attendees all share created_at, and two people with the same name in
// one order is ordinary rather than exotic.
// Spec 022 FR-053: `search` is the operator's recovery route, not a convenience.
// A registrant is never shown the address their e-ticket went to (FR-039), so an
// operator helping someone who never received it cannot be given the exact
// address to look up. Matching a PARTIAL name or email is therefore the only
// thing that turns "I registered and nothing arrived" into a resend.
//
// ILIKE with leading wildcards cannot use a btree index and will seq-scan. That
// is accepted: this is an authenticated, low-frequency admin read, unlike the
// registration write path where a scan sat inside a quota row lock.
func (q *Queries) ListAttendeesAdmin(ctx context.Context, arg ListAttendeesAdminParams) ([]ListAttendeesAdminRow, error) {
	rows, err := q.db.Query(ctx, listAttendeesAdmin,
		arg.OrderID,
		arg.TicketTypeIds,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendeesAdminRow{}
	for rows.Next() {
		var i ListAttendeesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TicketTypeID,
			&i.Name,
			&i.Email,
			&i.OrderNumber,
			&i.IsRegistration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendeesByOrderID = `-- name: ListAttendeesByOrderID :many
SELECT id, order_id, ticket_type_id, package_id, name, email
FROM attendees
WHERE order_id = $1
ORDER BY id ASC
`

type ListAttendeesByOrderIDRow struct {
	ID           uuid.UUID
	OrderID      uuid.UUID
	TicketTypeID uuid.UUID
	PackageID    uuid.NullUUID
	Name         *string
	Email        *string
}

func (q *Queries) ListAttendeesByOrderID(ctx context.Context, orderID uuid.UUID) ([]ListAttendeesByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listAttendeesByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendeesByOrderIDRow{}
	for rows.Next() {
		var i ListAttendeesByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TicketTypeID,
			&i.PackageID,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFees = `-- name: ListFees :many
SELECT id, name, fee_type, value, position, is_active, created_at, updated_at
FROM fees
ORDER BY position, name, id
LIMIT $2::int OFFSET $1::int
`

type ListFeesParams struct {
	RowOffset int32
	RowLimit  int32
}

// Admin read: every fee, active or not. `id` last for the same total-ordering
// reason as the lists above — two fees may share a position and a name.
func (q *Queries) ListFees(ctx context.Context, arg ListFeesParams) ([]Fee, error) {
	rows, err := q.db.Query(ctx, listFees, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fee{}
	for rows.Next() {
		var i Fee
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FeeType,
			&i.Value,
			&i.Position,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenders = `-- name: ListGenders :many
SELECT id, name, is_active FROM genders ORDER BY name
`

type ListGendersRow struct {
	ID       int16
	Name     string
	IsActive bool
}

// Every gender, active or not, as checkout needs it (spec 011 FR-031, clarified
// 2026-08-19). Deactivating an entry never rewrites a stored reference, so a
// restored form can submit a gender this list still knows and ListActiveGenders
// no longer offers. Checkout resolves gender_id from here — the active-only map
// yields the zero value for a retired name, which is an invalid foreign key
// rather than a refusal.
func (q *Queries) ListGenders(ctx context.Context) ([]ListGendersRow, error) {
	rows, err := q.db.Query(ctx, listGenders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGendersRow{}
	for rows.Next() {
		var i ListGendersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IsActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderFeesByOrderID = `-- name: ListOrderFeesByOrderID :many
SELECT id, name, amount, position
FROM order_fees
WHERE order_id = $1
ORDER BY position, name
`

type ListOrderFeesByOrderIDRow struct {
	ID       uuid.UUID
	Name     string
	Amount   decimal.Decimal
	Position int32
}

func (q *Queries) ListOrderFeesByOrderID(ctx context.Context, orderID uuid.UUID) ([]ListOrderFeesByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listOrderFeesByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderFeesByOrderIDRow{}
	for rows.Next() {
		var i ListOrderFeesByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, ticket_type_id, package_id, quantity, price
FROM order_items
WHERE order_id = $1
`

type ListOrderItemsByOrderIDRow struct {
	ID           uuid.UUID
	OrderID      uuid.UUID
	TicketTypeID uuid.NullUUID
	PackageID    uuid.NullUUID
	Quantity     int32
	Price        decimal.Decimal
}

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]ListOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsByOrderIDRow{}
	for rows.Next() {
		var i ListOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TicketTypeID,
			&i.PackageID,
			&i.Quantity,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersAdmin = `-- name: ListOrdersAdmin :many
SELECT o.id, o.order_number, o.buyer_name, o.buyer_email, o.buyer_phone, o.total_amount,
       os.name AS status,
       o.payment_provider, o.payment_url, o.email_sent,
       EXISTS (
           SELECT 1 FROM order_items oi
           JOIN ticket_types tt ON tt.id = oi.ticket_type_id
           WHERE oi.order_id = o.id AND NOT tt.is_visible
       ) AS is_registration,
       o.created_at, o.updated_at
FROM orders o
JOIN order_statuses os ON os.id = o.status_id
WHERE ($1::text IS NULL OR os.name = $1::text)
  AND (
        $2::uuid[] IS NULL
        OR EXISTS (
            SELECT 1 FROM order_items oi
            WHERE oi.order_id = o.id
              AND oi.ticket_type_id = ANY($2::uuid[])
        )
      )
  AND (
        $3::text IS NULL
        OR o.order_number ILIKE '%' || $3::text || '%'
        OR o.buyer_name   ILIKE '%' || $3::text || '%'
        OR o.buyer_email  ILIKE '%' || $3::text || '%'
      )
ORDER BY o.created_at DESC, o.id DESC
LIMIT $5::int OFFSET $4::int
`

type ListOrdersAdminParams struct {
	Status        *string
	TicketTypeIds []uuid.UUID
	Search        *string
	RowOffset     int32
	RowLimit      int32
}

type ListOrdersAdminRow struct {
	ID              uuid.UUID
	OrderNumber     string
	BuyerName       *string
	BuyerEmail      *string
	BuyerPhone      *string
	TotalAmount     decimal.Decimal
	Status          string
	PaymentProvider *string
	PaymentUrl      *string
	EmailSent       *bool
	IsRegistration  bool
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
}

// The `status` filter parameter is still the NAME the admin UI sends; it is
// matched against the joined master row rather than a column on orders.
func (q *Queries) ListOrdersAdmin(ctx context.Context, arg ListOrdersAdminParams) ([]ListOrdersAdminRow, error) {
	rows, err := q.db.Query(ctx, listOrdersAdmin,
		arg.Status,
		arg.TicketTypeIds,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersAdminRow{}
	for rows.Next() {
		var i ListOrdersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.BuyerName,
			&i.BuyerEmail,
			&i.BuyerPhone,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentProvider,
			&i.PaymentUrl,
			&i.EmailSent,
			&i.IsRegistration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersDueForExpiry = `-- name: ListOrdersDueForExpiry :many
SELECT o.id, o.order_number, os.name AS status, o.payment_expires_at
FROM orders o
JOIN order_statuses os ON os.id = o.status_id
WHERE o.status_id = 1 -- PENDING, pinned by migration 0013; see above
  AND o.payment_expires_at IS NOT NULL
  AND o.payment_expires_at <= $1
ORDER BY o.payment_expires_at
LIMIT $2
`

type ListOrdersDueForExpiryParams struct {
	PaymentExpiresAt *time.Time
	Limit            int32
}

type ListOrdersDueForExpiryRow struct {
	ID               uuid.UUID
	OrderNumber      string
	Status           string
	PaymentExpiresAt *time.Time
}

// Orders whose payment deadline has passed but which nothing has moved yet.
// Oldest first, so the longest-held quota is released soonest. Uses the partial
// index idx_orders_payment_expiry, which covers exactly this predicate.
//
// THE ONE PLACE THE LITERAL ID IS REQUIRED. Everywhere else the status name is
// resolved with a subquery; here it cannot be. A partial index predicate must
// be immutable, so the index is defined `WHERE status_id = 1`, and PostgreSQL
// only matches a partial index when the query predicate provably implies it at
// PLAN time. A subquery is a runtime value, so `status_id = (SELECT …)` would
// silently stop using the index and turn every sweeper tick into a sequential
// scan of the whole order history. That is why migration 0013 pins the seeded
// ids and SCHEMA.md documents 1 = PENDING as part of the contract (research R20).
func (q *Queries) ListOrdersDueForExpiry(ctx context.Context, arg ListOrdersDueForExpiryParams) ([]ListOrdersDueForExpiryRow, error) {
	rows, err := q.db.Query(ctx, listOrdersDueForExpiry, arg.PaymentExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersDueForExpiryRow{}
	for rows.Next() {
		var i ListOrdersDueForExpiryRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.Status,
			&i.PaymentExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotaHoldsByOrderID = `-- name: ListQuotaHoldsByOrderID :many
SELECT ticket_type_id, SUM(qty)::int AS qty
FROM (
    SELECT oi.ticket_type_id, oi.quantity AS qty
    FROM order_items oi
    WHERE oi.order_id = $1 AND oi.ticket_type_id IS NOT NULL

    UNION ALL

    SELECT pt.ticket_type_id, oi.quantity * pt.quantity AS qty
    FROM order_items oi
    JOIN package_tickets pt ON pt.package_id = oi.package_id
    WHERE oi.order_id = $1 AND oi.package_id IS NOT NULL
) holds
GROUP BY ticket_type_id
ORDER BY ticket_type_id
`

type ListQuotaHoldsByOrderIDRow struct {
	TicketTypeID uuid.NullUUID
	Qty          int32
}

// An order's total per-ticket-type hold, expanding package lines through the
// junction. This is the exact inverse of the checkout aggregation, so restoring
// returns precisely what deducting took.
//
// ORDER BY ticket_type_id matches the deduction order, keeping restore on the same
// deterministic lock sequence and out of deadlock range.
//
// It reconstructs the hold from the package's CURRENT composition, which is why
// composition edits are rejected while a PENDING order exists (research.md R-004).
func (q *Queries) ListQuotaHoldsByOrderID(ctx context.Context, orderID uuid.UUID) ([]ListQuotaHoldsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listQuotaHoldsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuotaHoldsByOrderIDRow{}
	for rows.Next() {
		var i ListQuotaHoldsByOrderIDRow
		if err := rows.Scan(&i.TicketTypeID, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderNumberExists = `-- name: OrderNumberExists :one
SELECT EXISTS (SELECT 1 FROM orders WHERE order_number = $1) AS taken
`

func (q *Queries) OrderNumberExists(ctx context.Context, orderNumber string) (bool, error) {
	row := q.db.QueryRow(ctx, orderNumberExists, orderNumber)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const recordTermsAgreement = `-- name: RecordTermsAgreement :execrows
UPDATE orders
SET terms_agreed_at = now(), event_terms_id = $2, updated_at = now()
WHERE orders.id = $1 AND status_id = (SELECT ost.id FROM order_statuses ost WHERE ost.name = 'PENDING')
`

type RecordTermsAgreementParams struct {
	ID           uuid.UUID
	EventTermsID uuid.NullUUID
}

// Same "Agree" click as booking, its own call. Guarded on PENDING; idempotent
// because re-stamping the same agreement is harmless.
func (q *Queries) RecordTermsAgreement(ctx context.Context, arg RecordTermsAgreementParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordTermsAgreement, arg.ID, arg.EventTermsID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEmailSent = `-- name: SetEmailSent :execrows
UPDATE orders SET email_sent = TRUE, updated_at = now() WHERE id = $1
`

func (q *Queries) SetEmailSent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, setEmailSent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const soldCountByPackage = `-- name: SoldCountByPackage :many
SELECT package_id, SUM(quantity)::bigint AS sold
FROM order_items
WHERE package_id = ANY($1::uuid[])
GROUP BY package_id
`

type SoldCountByPackageRow struct {
	PackageID uuid.NullUUID
	Sold      int64
}

// Derived count of how many units of each package have been sold, used by the
// admin package dashboard. A package line is stored once at the package's own
// price, so the count is a straight SUM(quantity) over order_items, no expansion.
func (q *Queries) SoldCountByPackage(ctx context.Context, ids []uuid.UUID) ([]SoldCountByPackageRow, error) {
	rows, err := q.db.Query(ctx, soldCountByPackage, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SoldCountByPackageRow{}
	for rows.Next() {
		var i SoldCountByPackageRow
		if err := rows.Scan(&i.PackageID, &i.Sold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const soldCountByTicketTypes = `-- name: SoldCountByTicketTypes :many
SELECT ticket_type_id, SUM(qty)::bigint AS sold
FROM (
    SELECT oi.ticket_type_id, oi.quantity AS qty
    FROM order_items oi
    WHERE oi.ticket_type_id = ANY($1::uuid[])

    UNION ALL

    SELECT pt.ticket_type_id, oi.quantity * pt.quantity AS qty
    FROM order_items oi
    JOIN package_tickets pt ON pt.package_id = oi.package_id
    WHERE oi.package_id IS NOT NULL
      AND pt.ticket_type_id = ANY($1::uuid[])
) sales
GROUP BY ticket_type_id
`

type SoldCountByTicketTypesRow struct {
	TicketTypeID uuid.NullUUID
	Sold         int64
}

// Derived, never stored (constitution, Critical Data Flow Rules). Batched over a
// whole page of ticket types so admin listings issue one query, not N.
//
// The UNION arm is not optional: a package line carries no ticket_type_id, so a
// count reading only the first arm would under-report every bundled sale.
func (q *Queries) SoldCountByTicketTypes(ctx context.Context, ids []uuid.UUID) ([]SoldCountByTicketTypesRow, error) {
	rows, err := q.db.Query(ctx, soldCountByTicketTypes, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SoldCountByTicketTypesRow{}
	for rows.Next() {
		var i SoldCountByTicketTypesRow
		if err := rows.Scan(&i.TicketTypeID, &i.Sold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttendeeDetails = `-- name: UpdateAttendeeDetails :execrows
UPDATE attendees
SET name = $3, email = $4, phone = $5, dob = $6, gender_id = $7
WHERE id = $1 AND order_id = $2
`

type UpdateAttendeeDetailsParams struct {
	ID       uuid.UUID
	OrderID  uuid.UUID
	Name     *string
	Email    *string
	Phone    *string
	Dob      pgtype.Date
	GenderID *int16
}

// Checkout TX-D: fills one slot. order_id in the predicate stops a forged slot
// id from writing into another order's attendee. gender_id references the
// master row whose NAME the request carried (spec 011, FR-018).
func (q *Queries) UpdateAttendeeDetails(ctx context.Context, arg UpdateAttendeeDetailsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAttendeeDetails,
		arg.ID,
		arg.OrderID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Dob,
		arg.GenderID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFee = `-- name: UpdateFee :one
UPDATE fees
SET name = $2, fee_type = $3, value = $4, position = $5, is_active = $6, updated_at = now()
WHERE id = $1
RETURNING id, name, fee_type, value, position, is_active, created_at, updated_at
`

type UpdateFeeParams struct {
	ID       uuid.UUID
	Name     string
	FeeType  string
	Value    decimal.Decimal
	Position int32
	IsActive bool
}

func (q *Queries) UpdateFee(ctx context.Context, arg UpdateFeeParams) (Fee, error) {
	row := q.db.QueryRow(ctx, updateFee,
		arg.ID,
		arg.Name,
		arg.FeeType,
		arg.Value,
		arg.Position,
		arg.IsActive,
	)
	var i Fee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FeeType,
		&i.Value,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderBuyer = `-- name: UpdateOrderBuyer :execrows
UPDATE orders
SET buyer_name = $2, buyer_email = $3, buyer_phone = $4, updated_at = now()
WHERE orders.id = $1 AND status_id = (SELECT ost.id FROM order_statuses ost WHERE ost.name = 'PENDING')
`

type UpdateOrderBuyerParams struct {
	ID         uuid.UUID
	BuyerName  *string
	BuyerEmail *string
	BuyerPhone *string
}

// Checkout TX-D: the primary contact — a snapshot of the TOPMOST holder form
// (first slot group in canonical slot order, spec 011). Only what downstream
// consumes is kept: name/email/phone (gateway customer, admin list, delivery
// fallback).
func (q *Queries) UpdateOrderBuyer(ctx context.Context, arg UpdateOrderBuyerParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderBuyer,
		arg.ID,
		arg.BuyerName,
		arg.BuyerEmail,
		arg.BuyerPhone,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrderStatusFromReleased = `-- name: UpdateOrderStatusFromReleased :execrows
UPDATE orders
SET status_id = (SELECT ost.id FROM order_statuses ost WHERE ost.name = $2),
    updated_at = now()
WHERE orders.id = $1
  AND status_id = (SELECT ost.id FROM order_statuses ost WHERE ost.name = $3)
`

type UpdateOrderStatusFromReleasedParams struct {
	ID         uuid.UUID
	Status     string
	FromStatus string
}

// Settle-after-expiry only (FR-019): move an order out of a RELEASED state into
// PAID because the gateway redelivered a notification saying it was paid.
//
// The query can express any from→to move; the payment domain cannot ask for one.
// Its adapter binds both statuses at the call site to EXPIRED → PAID, which is
// what makes FR-019d — never revive an order the gateway itself cancelled —
// unreachable by construction rather than by a caller remembering the rule.
//
// Guarded on the order still being in the state the caller saw, for the same
// reason UpdateOrderStatusIfPending is guarded on PENDING: two deliveries of the
// same resend must produce one transition, not two, or the re-deduction that
// accompanies it would run twice and oversell.
//
// Nothing here is reachable by a person asserting a payment. FR-022d forbids that
// outright, and there is no endpoint, service method, or interface that offers it.
func (q *Queries) UpdateOrderStatusFromReleased(ctx context.Context, arg UpdateOrderStatusFromReleasedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatusFromReleased, arg.ID, arg.Status, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrderStatusIfPending = `-- name: UpdateOrderStatusIfPending :execrows
UPDATE orders
SET status_id = (SELECT ost.id FROM order_statuses ost WHERE ost.name = $2),
    updated_at = now()
WHERE orders.id = $1
  AND status_id = (SELECT ost.id FROM order_statuses ost WHERE ost.name = 'PENDING')
`

type UpdateOrderStatusIfPendingParams struct {
	ID     uuid.UUID
	Status string
}

// Guarded on PENDING so a replayed webhook notification cannot apply the same
// transition (and its quota restoration) twice.
//
// Migration 0013 moved the column to a reference, but the caller still passes a
// NAME: the resolution happens here, in the statement, which is what keeps every
// Go status comparison in the codebase unchanged (spec 011 FR-026, research
// R19). Still one atomic statement, so the idempotency guard is unweakened.
func (q *Queries) UpdateOrderStatusIfPending(ctx context.Context, arg UpdateOrderStatusIfPendingParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatusIfPending, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePaymentDetails = `-- name: UpdatePaymentDetails :execrows

UPDATE orders
SET payment_url = $2,
    payment_provider = $3,
    payment_qr_string = $4,
    payment_expires_at = $5,
    updated_at = now()
WHERE id = $1
`

type UpdatePaymentDetailsParams struct {
	ID               uuid.UUID
	PaymentUrl       *string
	PaymentProvider  *string
	PaymentQrString  *string
	PaymentExpiresAt *time.Time
}

// Payment lifecycle --------------------------------------------------------
// Stamps everything the guest's payment page needs: the provider's QR-image URL
// (audit/fallback), the raw QRIS payload the image is rendered from, and the
// deadline the countdown and the expiry sweeper both read.
func (q *Queries) UpdatePaymentDetails(ctx context.Context, arg UpdatePaymentDetailsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePaymentDetails,
		arg.ID,
		arg.PaymentUrl,
		arg.PaymentProvider,
		arg.PaymentQrString,
		arg.PaymentExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePaymentDetailsIfUnstarted = `-- name: UpdatePaymentDetailsIfUnstarted :execrows
UPDATE orders
SET payment_url = $2,
    payment_provider = $3,
    payment_qr_string = $4,
    payment_expires_at = $5,
    updated_at = now()
WHERE orders.id = $1
  AND status_id = (SELECT ost.id FROM order_statuses ost WHERE ost.name = 'PENDING')
  AND payment_qr_string IS NULL
`

type UpdatePaymentDetailsIfUnstartedParams struct {
	ID               uuid.UUID
	PaymentUrl       *string
	PaymentProvider  *string
	PaymentQrString  *string
	PaymentExpiresAt *time.Time
}

// Checkout TX-P: stamps the gateway session and the payment window, guarded so
// a concurrent checkout cannot overwrite a live QR.
func (q *Queries) UpdatePaymentDetailsIfUnstarted(ctx context.Context, arg UpdatePaymentDetailsIfUnstartedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePaymentDetailsIfUnstarted,
		arg.ID,
		arg.PaymentUrl,
		arg.PaymentProvider,
		arg.PaymentQrString,
		arg.PaymentExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
