// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package adminsql

import (
	"context"

	"github.com/google/uuid"
)

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash
FROM admins
WHERE email = $1
`

type GetAdminByEmailRow struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
}

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (GetAdminByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i GetAdminByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}
