// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package paymentsql

import (
	"time"

	"github.com/google/uuid"
)

type Payment struct {
	ID            uuid.UUID
	OrderID       uuid.UUID
	Provider      string
	TransactionID string
	PaymentType   *string
	Status        string
	RawResponse   []byte
	CreatedAt     *time.Time
}
