// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package paymentsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, provider, transaction_id, payment_type, status, raw_response)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, provider, transaction_id, payment_type, status, created_at
`

type CreatePaymentParams struct {
	OrderID       uuid.UUID
	Provider      string
	TransactionID string
	PaymentType   *string
	Status        string
	RawResponse   []byte
}

type CreatePaymentRow struct {
	ID            uuid.UUID
	OrderID       uuid.UUID
	Provider      string
	TransactionID string
	PaymentType   *string
	Status        string
	CreatedAt     *time.Time
}

// One row per notification received. `status` stores the provider's RAW
// transaction_status (so `deny` stays distinguishable from `failure` even though
// both fold into orders.status = 'CANCELLED'), and raw_response keeps the full
// payload for audit.
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Provider,
		arg.TransactionID,
		arg.PaymentType,
		arg.Status,
		arg.RawResponse,
	)
	var i CreatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.TransactionID,
		&i.PaymentType,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
