// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package paymentsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countReissuedQRs = `-- name: CountReissuedQRs :one
SELECT COUNT(*) FROM payments WHERE order_id = $1 AND status = 'QR_REISSUED'
`

// How many times the order's QR has been re-issued (spec 008 FR-015). Drives
// the -R{n} suffix on the provider reference.
func (q *Queries) CountReissuedQRs(ctx context.Context, orderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReissuedQRs, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, provider, transaction_id, payment_type, status, raw_response)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, provider, transaction_id, payment_type, status, created_at
`

type CreatePaymentParams struct {
	OrderID       uuid.UUID
	Provider      string
	TransactionID string
	PaymentType   *string
	Status        string
	RawResponse   []byte
}

type CreatePaymentRow struct {
	ID            uuid.UUID
	OrderID       uuid.UUID
	Provider      string
	TransactionID string
	PaymentType   *string
	Status        string
	CreatedAt     *time.Time
}

// One row per notification received. `payments.status` stores the provider's RAW
// transaction_status (so `deny` stays distinguishable from `failure` even though
// both fold into the order's CANCELLED status), and raw_response keeps the full
// payload for audit.
//
// Deliberately untouched by migration 0013: this is the provider's own status
// string, a different column with a different meaning from the order's status,
// which became a reference to the order-status master list. No query in this
// file reads or writes the `orders` table at all.
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Provider,
		arg.TransactionID,
		arg.PaymentType,
		arg.Status,
		arg.RawResponse,
	)
	var i CreatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.TransactionID,
		&i.PaymentType,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
