// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket.sql

package ticketsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countTicketsByOrderID = `-- name: CountTicketsByOrderID :one
SELECT COUNT(*)::bigint AS total FROM tickets WHERE order_id = $1
`

func (q *Queries) CountTicketsByOrderID(ctx context.Context, orderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTicketsByOrderID, orderID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (ticket_code, order_id, attendee_id, status)
VALUES ($1, $2, $3, 'ACTIVE')
RETURNING id, ticket_code, order_id, attendee_id, status, created_at
`

type CreateTicketParams struct {
	TicketCode string
	OrderID    uuid.UUID
	AttendeeID uuid.UUID
}

type CreateTicketRow struct {
	ID         uuid.UUID
	TicketCode string
	OrderID    uuid.UUID
	AttendeeID uuid.UUID
	Status     string
	CreatedAt  *time.Time
}

// qr_code_url is deliberately left NULL: this MVP has no object storage and QR
// images are rendered on demand from ticket_code (spec FR-022).
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (CreateTicketRow, error) {
	row := q.db.QueryRow(ctx, createTicket, arg.TicketCode, arg.OrderID, arg.AttendeeID)
	var i CreateTicketRow
	err := row.Scan(
		&i.ID,
		&i.TicketCode,
		&i.OrderID,
		&i.AttendeeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTicketDetailByCode = `-- name: GetTicketDetailByCode :one
SELECT t.ticket_code, t.status, a.name AS attendee_name,
       tt.name AS ticket_type_name, e.name AS event_name
FROM tickets t
JOIN attendees a ON a.id = t.attendee_id
JOIN ticket_types tt ON tt.id = a.ticket_type_id
JOIN events e ON e.id = tt.event_id
WHERE t.ticket_code = $1
`

type GetTicketDetailByCodeRow struct {
	TicketCode     string
	Status         string
	AttendeeName   *string
	TicketTypeName string
	EventName      string
}

// Exact match on the already-canonical stored code so idx_tickets_ticket_code is
// used; never UPPER(ticket_code) = ..., which would force a sequential scan.
func (q *Queries) GetTicketDetailByCode(ctx context.Context, ticketCode string) (GetTicketDetailByCodeRow, error) {
	row := q.db.QueryRow(ctx, getTicketDetailByCode, ticketCode)
	var i GetTicketDetailByCodeRow
	err := row.Scan(
		&i.TicketCode,
		&i.Status,
		&i.AttendeeName,
		&i.TicketTypeName,
		&i.EventName,
	)
	return i, err
}

const getTicketStatusByCode = `-- name: GetTicketStatusByCode :one
SELECT status FROM tickets WHERE ticket_code = $1
`

func (q *Queries) GetTicketStatusByCode(ctx context.Context, ticketCode string) (string, error) {
	row := q.db.QueryRow(ctx, getTicketStatusByCode, ticketCode)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listTicketDetailsByOrderID = `-- name: ListTicketDetailsByOrderID :many
SELECT t.ticket_code, t.status, a.name AS attendee_name,
       tt.name AS ticket_type_name, e.name AS event_name,
       e.venue, e.start_date
FROM tickets t
JOIN attendees a ON a.id = t.attendee_id
JOIN ticket_types tt ON tt.id = a.ticket_type_id
JOIN events e ON e.id = tt.event_id
WHERE t.order_id = $1
ORDER BY t.created_at ASC, t.ticket_code ASC
`

type ListTicketDetailsByOrderIDRow struct {
	TicketCode     string
	Status         string
	AttendeeName   *string
	TicketTypeName string
	EventName      string
	Venue          string
	StartDate      time.Time
}

// Everything the ticket PDF prints, for the initial delivery and every resend.
func (q *Queries) ListTicketDetailsByOrderID(ctx context.Context, orderID uuid.UUID) ([]ListTicketDetailsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listTicketDetailsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketDetailsByOrderIDRow{}
	for rows.Next() {
		var i ListTicketDetailsByOrderIDRow
		if err := rows.Scan(
			&i.TicketCode,
			&i.Status,
			&i.AttendeeName,
			&i.TicketTypeName,
			&i.EventName,
			&i.Venue,
			&i.StartDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByOrderID = `-- name: ListTicketsByOrderID :many
SELECT t.id, t.ticket_code, t.attendee_id, t.status
FROM tickets t
WHERE t.order_id = $1
ORDER BY t.created_at ASC, t.ticket_code ASC
`

type ListTicketsByOrderIDRow struct {
	ID         uuid.UUID
	TicketCode string
	AttendeeID uuid.UUID
	Status     string
}

func (q *Queries) ListTicketsByOrderID(ctx context.Context, orderID uuid.UUID) ([]ListTicketsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listTicketsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsByOrderIDRow{}
	for rows.Next() {
		var i ListTicketsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketCode,
			&i.AttendeeID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTicketUsed = `-- name: MarkTicketUsed :execrows
UPDATE tickets
SET status = 'USED', updated_at = now()
WHERE ticket_code = $1 AND status = 'ACTIVE'
`

// Single guarded UPDATE: two near-simultaneous calls cannot both succeed.
// updated_at records when the ticket was consumed — SCHEMA.md is LOCKED and the
// tickets table has no used_at column.
func (q *Queries) MarkTicketUsed(ctx context.Context, ticketCode string) (int64, error) {
	result, err := q.db.Exec(ctx, markTicketUsed, ticketCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
