// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package eventsql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const checkAndDeductQuota = `-- name: CheckAndDeductQuota :one

UPDATE ticket_types
SET quota = quota - $1, updated_at = now()
WHERE id = $2 AND quota >= $1
RETURNING quota
`

type CheckAndDeductQuotaParams struct {
	Qty int32
	ID  uuid.UUID
}

// Quota mutation (EventProvider) -------------------------------------------
// `quota` is the REMAINING quota (constitution, Critical Data Flow Rules): the live
// counter checkout decrements and cancel/expire/deny/failure restore. The guarded
// WHERE makes the deduction atomic under concurrency — zero rows affected means
// insufficient quota, never a negative value.
func (q *Queries) CheckAndDeductQuota(ctx context.Context, arg CheckAndDeductQuotaParams) (int32, error) {
	row := q.db.QueryRow(ctx, checkAndDeductQuota, arg.Qty, arg.ID)
	var quota int32
	err := row.Scan(&quota)
	return quota, err
}

const countPackagesByEventID = `-- name: CountPackagesByEventID :one
SELECT COUNT(*)::bigint AS total FROM packages WHERE event_id = $1
`

func (q *Queries) CountPackagesByEventID(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPackagesByEventID, eventID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (name, slug, description, venue, address, start_date, end_date, banner_url, status, scale)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, slug, description, venue, address, start_date, end_date, banner_url, status, created_at, updated_at, scale
`

type CreateEventParams struct {
	Name        string
	Slug        string
	Description *string
	Venue       string
	Address     string
	StartDate   time.Time
	EndDate     time.Time
	BannerUrl   *string
	Status      string
	Scale       *int64
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Venue,
		arg.Address,
		arg.StartDate,
		arg.EndDate,
		arg.BannerUrl,
		arg.Status,
		arg.Scale,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.Address,
		&i.StartDate,
		&i.EndDate,
		&i.BannerUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scale,
	)
	return i, err
}

const createEventActivity = `-- name: CreateEventActivity :one
INSERT INTO event_activities (event_id, title, description, icon, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, event_id, title, description, icon, position, created_at, updated_at
`

type CreateEventActivityParams struct {
	EventID     uuid.UUID
	Title       string
	Description string
	Icon        *string
	Position    int32
}

func (q *Queries) CreateEventActivity(ctx context.Context, arg CreateEventActivityParams) (EventActivity, error) {
	row := q.db.QueryRow(ctx, createEventActivity,
		arg.EventID,
		arg.Title,
		arg.Description,
		arg.Icon,
		arg.Position,
	)
	var i EventActivity
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventGuestStar = `-- name: CreateEventGuestStar :one
INSERT INTO event_guest_stars (event_id, name, position)
VALUES ($1, $2, $3)
RETURNING id, event_id, name, position, created_at, updated_at
`

type CreateEventGuestStarParams struct {
	EventID  uuid.UUID
	Name     string
	Position int32
}

func (q *Queries) CreateEventGuestStar(ctx context.Context, arg CreateEventGuestStarParams) (EventGuestStar, error) {
	row := q.db.QueryRow(ctx, createEventGuestStar, arg.EventID, arg.Name, arg.Position)
	var i EventGuestStar
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventGuideline = `-- name: CreateEventGuideline :one
INSERT INTO event_guidelines (event_id, description, icon, position)
VALUES ($1, $2, $3, $4)
RETURNING id, event_id, description, icon, position, created_at, updated_at
`

type CreateEventGuidelineParams struct {
	EventID     uuid.UUID
	Description string
	Icon        *string
	Position    int32
}

func (q *Queries) CreateEventGuideline(ctx context.Context, arg CreateEventGuidelineParams) (EventGuideline, error) {
	row := q.db.QueryRow(ctx, createEventGuideline,
		arg.EventID,
		arg.Description,
		arg.Icon,
		arg.Position,
	)
	var i EventGuideline
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Description,
		&i.Icon,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPackage = `-- name: CreatePackage :one
INSERT INTO packages (event_id, name, description, price, sales_start, sales_end, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, event_id, name, description, price, sales_start, sales_end, is_active,
          created_at, updated_at
`

type CreatePackageParams struct {
	EventID     uuid.UUID
	Name        string
	Description *string
	Price       decimal.Decimal
	SalesStart  time.Time
	SalesEnd    time.Time
	IsActive    bool
}

type CreatePackageRow struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Name        string
	Description *string
	Price       decimal.Decimal
	SalesStart  time.Time
	SalesEnd    time.Time
	IsActive    bool
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

// No quota column is written because none exists.
func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (CreatePackageRow, error) {
	row := q.db.QueryRow(ctx, createPackage,
		arg.EventID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.SalesStart,
		arg.SalesEnd,
		arg.IsActive,
	)
	var i CreatePackageRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.SalesStart,
		&i.SalesEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPackageComponent = `-- name: CreatePackageComponent :one
INSERT INTO package_tickets (package_id, ticket_type_id, event_id, quantity)
VALUES ($1, $2, $3, $4)
RETURNING id, package_id, ticket_type_id, event_id, quantity, created_at
`

type CreatePackageComponentParams struct {
	PackageID    uuid.UUID
	TicketTypeID uuid.UUID
	EventID      uuid.UUID
	Quantity     int32
}

// event_id is supplied by the caller and is what the two composite foreign keys
// both resolve against, making cross-event composition impossible to insert.
func (q *Queries) CreatePackageComponent(ctx context.Context, arg CreatePackageComponentParams) (PackageTicket, error) {
	row := q.db.QueryRow(ctx, createPackageComponent,
		arg.PackageID,
		arg.TicketTypeID,
		arg.EventID,
		arg.Quantity,
	)
	var i PackageTicket
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.TicketTypeID,
		&i.EventID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const createTicketType = `-- name: CreateTicketType :one
INSERT INTO ticket_types (event_id, name, description, price, quota, sales_start, sales_end, event_start, event_end)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, event_id, name, description, price, quota, sales_start, sales_end, event_start, event_end, created_at, updated_at
`

type CreateTicketTypeParams struct {
	EventID     uuid.UUID
	Name        string
	Description *string
	Price       decimal.Decimal
	Quota       int32
	SalesStart  time.Time
	SalesEnd    time.Time
	EventStart  time.Time
	EventEnd    time.Time
}

type CreateTicketTypeRow struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Name        string
	Description *string
	Price       decimal.Decimal
	Quota       int32
	SalesStart  time.Time
	SalesEnd    time.Time
	EventStart  time.Time
	EventEnd    time.Time
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

func (q *Queries) CreateTicketType(ctx context.Context, arg CreateTicketTypeParams) (CreateTicketTypeRow, error) {
	row := q.db.QueryRow(ctx, createTicketType,
		arg.EventID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Quota,
		arg.SalesStart,
		arg.SalesEnd,
		arg.EventStart,
		arg.EventEnd,
	)
	var i CreateTicketTypeRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quota,
		&i.SalesStart,
		&i.SalesEnd,
		&i.EventStart,
		&i.EventEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :execrows
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEventActivity = `-- name: DeleteEventActivity :execrows
DELETE FROM event_activities WHERE id = $1 AND event_id = $2
`

type DeleteEventActivityParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) DeleteEventActivity(ctx context.Context, arg DeleteEventActivityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventActivity, arg.ID, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEventGuestStar = `-- name: DeleteEventGuestStar :execrows
DELETE FROM event_guest_stars WHERE id = $1 AND event_id = $2
`

type DeleteEventGuestStarParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) DeleteEventGuestStar(ctx context.Context, arg DeleteEventGuestStarParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventGuestStar, arg.ID, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEventGuideline = `-- name: DeleteEventGuideline :execrows
DELETE FROM event_guidelines WHERE id = $1 AND event_id = $2
`

type DeleteEventGuidelineParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) DeleteEventGuideline(ctx context.Context, arg DeleteEventGuidelineParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventGuideline, arg.ID, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePackage = `-- name: DeletePackage :execrows
DELETE FROM packages WHERE id = $1
`

func (q *Queries) DeletePackage(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePackage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePackageComponents = `-- name: DeletePackageComponents :execrows
DELETE FROM package_tickets WHERE package_id = $1
`

func (q *Queries) DeletePackageComponents(ctx context.Context, packageID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePackageComponents, packageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTicketType = `-- name: DeleteTicketType :execrows
DELETE FROM ticket_types WHERE id = $1
`

func (q *Queries) DeleteTicketType(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTicketType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTicketTypesByEventID = `-- name: DeleteTicketTypesByEventID :execrows
DELETE FROM ticket_types WHERE event_id = $1
`

func (q *Queries) DeleteTicketTypesByEventID(ctx context.Context, eventID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTicketTypesByEventID, eventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eventHasTerms = `-- name: EventHasTerms :one
SELECT EXISTS (SELECT 1 FROM event_terms WHERE event_id = $1) AS has_terms
`

func (q *Queries) EventHasTerms(ctx context.Context, eventID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, eventHasTerms, eventID)
	var has_terms bool
	err := row.Scan(&has_terms)
	return has_terms, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, name, slug, description, venue, address, start_date, end_date, banner_url, status, created_at, updated_at, scale
FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.Address,
		&i.StartDate,
		&i.EndDate,
		&i.BannerUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scale,
	)
	return i, err
}

const getEventTermsByEventID = `-- name: GetEventTermsByEventID :one

SELECT id, event_id, content, created_at, updated_at
FROM event_terms
WHERE event_id = $1
`

// Spec 008: Terms & Conditions ----------------------------------------------
func (q *Queries) GetEventTermsByEventID(ctx context.Context, eventID uuid.UUID) (EventTerm, error) {
	row := q.db.QueryRow(ctx, getEventTermsByEventID, eventID)
	var i EventTerm
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventTermsByEventSlug = `-- name: GetEventTermsByEventSlug :one
SELECT t.id, t.event_id, t.content, t.created_at, t.updated_at
FROM event_terms t
JOIN events e ON e.id = t.event_id
WHERE e.slug = $1 AND e.status = 'PUBLISHED'
`

// Guest read: the dialog fetches terms by the event's public identifier.
func (q *Queries) GetEventTermsByEventSlug(ctx context.Context, slug string) (EventTerm, error) {
	row := q.db.QueryRow(ctx, getEventTermsByEventSlug, slug)
	var i EventTerm
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPackageAvailability = `-- name: GetPackageAvailability :one
SELECT
    COALESCE(MIN(tt.quota / pt.quantity), 0)::int AS available_units,
    COALESCE(
        (ARRAY_AGG(tt.id ORDER BY (tt.quota / pt.quantity) ASC, tt.id ASC))[1],
        '00000000-0000-0000-0000-000000000000'::uuid
    )::uuid AS limiting_ticket_type_id,
    COUNT(*)::int AS component_count,
    COALESCE(BOOL_AND(tt.sales_start <= now() AND tt.sales_end >= now()), FALSE)::boolean
        AS all_components_on_sale
FROM package_tickets pt
JOIN ticket_types tt ON tt.id = pt.ticket_type_id
WHERE pt.package_id = $1
`

type GetPackageAvailabilityRow struct {
	AvailableUnits       int32
	LimitingTicketTypeID uuid.UUID
	ComponentCount       int32
	AllComponentsOnSale  bool
}

// Single-package form, for the admin availability diagnostic.
//
// The aggregates are COALESCEd because a componentless package groups over zero
// rows and would otherwise return NULLs that fail to scan. component_count = 0 is
// the signal callers read as "no composition, therefore unavailable"; a NIL
// limiting id means the same.
func (q *Queries) GetPackageAvailability(ctx context.Context, packageID uuid.UUID) (GetPackageAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, getPackageAvailability, packageID)
	var i GetPackageAvailabilityRow
	err := row.Scan(
		&i.AvailableUnits,
		&i.LimitingTicketTypeID,
		&i.ComponentCount,
		&i.AllComponentsOnSale,
	)
	return i, err
}

const getPackageByID = `-- name: GetPackageByID :one
SELECT id, event_id, name, description, price, sales_start, sales_end, is_active,
       created_at, updated_at
FROM packages
WHERE id = $1
`

type GetPackageByIDRow struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Name        string
	Description *string
	Price       decimal.Decimal
	SalesStart  time.Time
	SalesEnd    time.Time
	IsActive    bool
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

func (q *Queries) GetPackageByID(ctx context.Context, id uuid.UUID) (GetPackageByIDRow, error) {
	row := q.db.QueryRow(ctx, getPackageByID, id)
	var i GetPackageByIDRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.SalesStart,
		&i.SalesEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedEventBySlug = `-- name: GetPublishedEventBySlug :one
SELECT id, name, slug, description, venue, address, start_date, end_date, banner_url, status, scale
FROM events
WHERE slug = $1 AND status = 'PUBLISHED'
`

type GetPublishedEventBySlugRow struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description *string
	Venue       string
	Address     string
	StartDate   time.Time
	EndDate     time.Time
	BannerUrl   *string
	Status      string
	Scale       *int64
}

func (q *Queries) GetPublishedEventBySlug(ctx context.Context, slug string) (GetPublishedEventBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublishedEventBySlug, slug)
	var i GetPublishedEventBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.Address,
		&i.StartDate,
		&i.EndDate,
		&i.BannerUrl,
		&i.Status,
		&i.Scale,
	)
	return i, err
}

const getTicketTypeAdmin = `-- name: GetTicketTypeAdmin :one
SELECT id, event_id, name, description, price, quota, sales_start, sales_end, event_start, event_end, created_at, updated_at
FROM ticket_types
WHERE id = $1
`

type GetTicketTypeAdminRow struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Name        string
	Description *string
	Price       decimal.Decimal
	Quota       int32
	SalesStart  time.Time
	SalesEnd    time.Time
	EventStart  time.Time
	EventEnd    time.Time
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

func (q *Queries) GetTicketTypeAdmin(ctx context.Context, id uuid.UUID) (GetTicketTypeAdminRow, error) {
	row := q.db.QueryRow(ctx, getTicketTypeAdmin, id)
	var i GetTicketTypeAdminRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quota,
		&i.SalesStart,
		&i.SalesEnd,
		&i.EventStart,
		&i.EventEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketTypeByID = `-- name: GetTicketTypeByID :one
SELECT id, event_id, name, description, price, quota, sales_start, sales_end, event_start, event_end
FROM ticket_types
WHERE id = $1
`

type GetTicketTypeByIDRow struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Name        string
	Description *string
	Price       decimal.Decimal
	Quota       int32
	SalesStart  time.Time
	SalesEnd    time.Time
	EventStart  time.Time
	EventEnd    time.Time
}

func (q *Queries) GetTicketTypeByID(ctx context.Context, id uuid.UUID) (GetTicketTypeByIDRow, error) {
	row := q.db.QueryRow(ctx, getTicketTypeByID, id)
	var i GetTicketTypeByIDRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quota,
		&i.SalesStart,
		&i.SalesEnd,
		&i.EventStart,
		&i.EventEnd,
	)
	return i, err
}

const listEventActivities = `-- name: ListEventActivities :many

SELECT id, event_id, title, description, icon, position, created_at, updated_at
FROM event_activities
WHERE event_id = $1
ORDER BY position ASC, created_at ASC
`

// Spec 008: content blocks --------------------------------------------------
func (q *Queries) ListEventActivities(ctx context.Context, eventID uuid.UUID) ([]EventActivity, error) {
	rows, err := q.db.Query(ctx, listEventActivities, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventActivity{}
	for rows.Next() {
		var i EventActivity
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Title,
			&i.Description,
			&i.Icon,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventGuestStars = `-- name: ListEventGuestStars :many
SELECT id, event_id, name, position, created_at, updated_at
FROM event_guest_stars
WHERE event_id = $1
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListEventGuestStars(ctx context.Context, eventID uuid.UUID) ([]EventGuestStar, error) {
	rows, err := q.db.Query(ctx, listEventGuestStars, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventGuestStar{}
	for rows.Next() {
		var i EventGuestStar
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventGuidelines = `-- name: ListEventGuidelines :many
SELECT id, event_id, description, icon, position, created_at, updated_at
FROM event_guidelines
WHERE event_id = $1
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListEventGuidelines(ctx context.Context, eventID uuid.UUID) ([]EventGuideline, error) {
	rows, err := q.db.Query(ctx, listEventGuidelines, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventGuideline{}
	for rows.Next() {
		var i EventGuideline
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Description,
			&i.Icon,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventIDsByTicketTypeIDs = `-- name: ListEventIDsByTicketTypeIDs :many
SELECT DISTINCT event_id FROM ticket_types WHERE id = ANY($1::uuid[])
`

// The inverse of ListTicketTypeIDsByEventID. The payment domain holds quota
// holds keyed by ticket type and needs the owning events to invalidate their
// cached lists; `orders` has no event_id column, so this is the resolution path.
// DISTINCT because an order's holds routinely span several ticket types of the
// same event.
func (q *Queries) ListEventIDsByTicketTypeIDs(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEventIDsByTicketTypeIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var event_id uuid.UUID
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many

SELECT id, name, slug, description, venue, address, start_date, end_date, banner_url, status, created_at, updated_at, scale
FROM events
ORDER BY start_date DESC
`

// Admin event CRUD ---------------------------------------------------------
func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Venue,
			&i.Address,
			&i.StartDate,
			&i.EndDate,
			&i.BannerUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageAdmissionStartsByIDs = `-- name: ListPackageAdmissionStartsByIDs :many
SELECT DISTINCT pt.package_id, tt.event_start
FROM package_tickets pt
JOIN ticket_types tt ON tt.id = pt.ticket_type_id
WHERE pt.package_id = ANY($1::uuid[])
ORDER BY pt.package_id, tt.event_start
`

type ListPackageAdmissionStartsByIDsRow struct {
	PackageID  uuid.UUID
	EventStart time.Time
}

// Every distinct day each bundle admits on, one row per (package, start).
//
// A separate query rather than an array_agg on the display row: aggregates lose
// their type in this sqlc configuration (MIN() generated interface{} until it was
// cast), and two plain queries keep every generated field a bare time.Time. Both
// tables are event-domain, so the join stays inside the boundary.
func (q *Queries) ListPackageAdmissionStartsByIDs(ctx context.Context, ids []uuid.UUID) ([]ListPackageAdmissionStartsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listPackageAdmissionStartsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackageAdmissionStartsByIDsRow{}
	for rows.Next() {
		var i ListPackageAdmissionStartsByIDsRow
		if err := rows.Scan(&i.PackageID, &i.EventStart); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageComponentsByPackageIDs = `-- name: ListPackageComponentsByPackageIDs :many
SELECT pt.package_id, pt.ticket_type_id, pt.quantity AS quantity_per_unit,
       tt.name AS ticket_type_name, tt.price, tt.quota, tt.sales_start, tt.sales_end
FROM package_tickets pt
JOIN ticket_types tt ON tt.id = pt.ticket_type_id
WHERE pt.package_id = ANY($1::uuid[])
ORDER BY pt.package_id, tt.name
`

type ListPackageComponentsByPackageIDsRow struct {
	PackageID       uuid.UUID
	TicketTypeID    uuid.UUID
	QuantityPerUnit int32
	TicketTypeName  string
	Price           decimal.Decimal
	Quota           int32
	SalesStart      time.Time
	SalesEnd        time.Time
}

// Batched over the whole list so rendering "what is inside this bundle" stays one
// query regardless of how many packages an event has.
func (q *Queries) ListPackageComponentsByPackageIDs(ctx context.Context, packageIds []uuid.UUID) ([]ListPackageComponentsByPackageIDsRow, error) {
	rows, err := q.db.Query(ctx, listPackageComponentsByPackageIDs, packageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackageComponentsByPackageIDsRow{}
	for rows.Next() {
		var i ListPackageComponentsByPackageIDsRow
		if err := rows.Scan(
			&i.PackageID,
			&i.TicketTypeID,
			&i.QuantityPerUnit,
			&i.TicketTypeName,
			&i.Price,
			&i.Quota,
			&i.SalesStart,
			&i.SalesEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageDisplaysByIDs = `-- name: ListPackageDisplaysByIDs :many
SELECT p.id, p.name, e.name AS event_name, e.slug AS event_slug,
       e.venue AS event_venue, e.address AS event_address,
       e.start_date AS event_start_date, e.end_date AS event_end_date
FROM packages p
JOIN events e ON e.id = p.event_id
WHERE p.id = ANY($1::uuid[])
`

type ListPackageDisplaysByIDsRow struct {
	ID             uuid.UUID
	Name           string
	EventName      string
	EventSlug      string
	EventVenue     string
	EventAddress   string
	EventStartDate time.Time
	EventEndDate   time.Time
}

// Both tables belong to this domain, so the JOIN stays inside the boundary the
// order domain is not allowed to cross itself.
//
// Carries no admission window: a bundle admits on every day its parts admit, and
// a single collapsed span cannot say that (spec 015 FR-021a). The days come from
// ListPackageAdmissionStartsByIDs below.
func (q *Queries) ListPackageDisplaysByIDs(ctx context.Context, ids []uuid.UUID) ([]ListPackageDisplaysByIDsRow, error) {
	rows, err := q.db.Query(ctx, listPackageDisplaysByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackageDisplaysByIDsRow{}
	for rows.Next() {
		var i ListPackageDisplaysByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventName,
			&i.EventSlug,
			&i.EventVenue,
			&i.EventAddress,
			&i.EventStartDate,
			&i.EventEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagesByTicketTypeID = `-- name: ListPackagesByTicketTypeID :many
SELECT p.id, p.name
FROM package_tickets pt
JOIN packages p ON p.id = pt.package_id
WHERE pt.ticket_type_id = $1
ORDER BY p.name
`

type ListPackagesByTicketTypeIDRow struct {
	ID   uuid.UUID
	Name string
}

// Drives the ticket-type delete guard: a ticket inside a bundle cannot be deleted
// until it is removed from that bundle. Returns names so the 400 can say which.
func (q *Queries) ListPackagesByTicketTypeID(ctx context.Context, ticketTypeID uuid.UUID) ([]ListPackagesByTicketTypeIDRow, error) {
	rows, err := q.db.Query(ctx, listPackagesByTicketTypeID, ticketTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackagesByTicketTypeIDRow{}
	for rows.Next() {
		var i ListPackagesByTicketTypeIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagesByTicketTypeIDs = `-- name: ListPackagesByTicketTypeIDs :many
SELECT DISTINCT p.id, p.name
FROM package_tickets pt
JOIN packages p ON p.id = pt.package_id
WHERE pt.ticket_type_id = ANY($1::uuid[])
ORDER BY p.name
`

type ListPackagesByTicketTypeIDsRow struct {
	ID   uuid.UUID
	Name string
}

// Batched form used when deleting an event, which must consider every ticket type.
func (q *Queries) ListPackagesByTicketTypeIDs(ctx context.Context, ids []uuid.UUID) ([]ListPackagesByTicketTypeIDsRow, error) {
	rows, err := q.db.Query(ctx, listPackagesByTicketTypeIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackagesByTicketTypeIDsRow{}
	for rows.Next() {
		var i ListPackagesByTicketTypeIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagesWithAvailabilityByEventID = `-- name: ListPackagesWithAvailabilityByEventID :many

WITH component_stats AS (
    SELECT
        pt.package_id,
        MIN(tt.quota / pt.quantity)::int AS available_units,
        (ARRAY_AGG(tt.id ORDER BY (tt.quota / pt.quantity) ASC, tt.id ASC))[1]::uuid
            AS limiting_ticket_type_id,
        BOOL_AND(tt.sales_start <= now() AND tt.sales_end >= now())
            AS all_components_on_sale,
        COUNT(*) AS component_count
    FROM package_tickets pt
    JOIN ticket_types tt ON tt.id = pt.ticket_type_id
    GROUP BY pt.package_id
)
SELECT
    p.id, p.event_id, p.name, p.description, p.price,
    p.sales_start, p.sales_end, p.is_active, p.created_at, p.updated_at,
    COALESCE(cs.available_units, 0)::int AS available_units,
    cs.limiting_ticket_type_id,
    (
        COALESCE(cs.available_units, 0) > 0
        AND COALESCE(cs.component_count, 0) > 0
        AND COALESCE(cs.all_components_on_sale, FALSE)
        AND p.is_active
        AND p.sales_start <= now()
        AND p.sales_end   >= now()
    ) AS purchasable
FROM packages p
LEFT JOIN component_stats cs ON cs.package_id = p.id
WHERE p.event_id = $1
ORDER BY p.price ASC, p.name ASC
`

type ListPackagesWithAvailabilityByEventIDRow struct {
	ID                   uuid.UUID
	EventID              uuid.UUID
	Name                 string
	Description          *string
	Price                decimal.Decimal
	SalesStart           time.Time
	SalesEnd             time.Time
	IsActive             bool
	CreatedAt            *time.Time
	UpdatedAt            *time.Time
	AvailableUnits       int32
	LimitingTicketTypeID uuid.NullUUID
	Purchasable          *bool
}

// Packages (bundle offers) --------------------------------------------------
// Owned by this domain: a package hangs off an event and joins only to that
// event's ticket_types, so nothing here crosses a domain boundary.
//
// There is deliberately no quota column to read or write. Availability is derived
// at read time from the remaining quota of the constituents reached through
// package_tickets; a stored figure would be a second source of truth.
// The booking-list query. Two queries serve the whole list (this one plus a batched
// component read), never N+1 across packages.
//
// available_units = MIN(quota / quantity_per_unit): integer division floors, so a
// constituent with 5 remaining consumed 2 at a time yields 2 whole sets, not 2.5.
// MIN because the scarcest constituent governs.
//
// purchasable folds every gate into one boolean so the client cannot disagree with
// the server about what is buyable: units > 0, at least one component, EVERY
// constituent on sale (the binding constraint), ACTIVE, and the package's own window.
//
// LEFT JOIN, not JOIN: a componentless package must still list to an administrator
// as broken rather than silently vanish.
func (q *Queries) ListPackagesWithAvailabilityByEventID(ctx context.Context, eventID uuid.UUID) ([]ListPackagesWithAvailabilityByEventIDRow, error) {
	rows, err := q.db.Query(ctx, listPackagesWithAvailabilityByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackagesWithAvailabilityByEventIDRow{}
	for rows.Next() {
		var i ListPackagesWithAvailabilityByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.SalesStart,
			&i.SalesEnd,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvailableUnits,
			&i.LimitingTicketTypeID,
			&i.Purchasable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEvents = `-- name: ListPublishedEvents :many

SELECT id, name, slug, description, venue, address, start_date, end_date, banner_url, status, scale
FROM events
WHERE status = 'PUBLISHED'
ORDER BY start_date ASC
`

type ListPublishedEventsRow struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description *string
	Venue       string
	Address     string
	StartDate   time.Time
	EndDate     time.Time
	BannerUrl   *string
	Status      string
	Scale       *int64
}

// Guest-facing reads -------------------------------------------------------
func (q *Queries) ListPublishedEvents(ctx context.Context) ([]ListPublishedEventsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedEventsRow{}
	for rows.Next() {
		var i ListPublishedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Venue,
			&i.Address,
			&i.StartDate,
			&i.EndDate,
			&i.BannerUrl,
			&i.Status,
			&i.Scale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPackagesByEventSlug = `-- name: ListPublishedPackagesByEventSlug :many
SELECT p.id
FROM packages p
JOIN events e ON e.id = p.event_id
WHERE e.slug = $1 AND e.status = 'PUBLISHED' AND p.is_active
`

// Guest-facing variant: only ACTIVE packages of a PUBLISHED event.
func (q *Queries) ListPublishedPackagesByEventSlug(ctx context.Context, slug string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPublishedPackagesByEventSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypeDisplaysByIDs = `-- name: ListTicketTypeDisplaysByIDs :many
SELECT tt.id, tt.name, e.name AS event_name, e.slug AS event_slug,
       e.venue AS event_venue, e.address AS event_address,
       e.start_date AS event_start_date, e.end_date AS event_end_date,
       tt.event_start AS ticket_event_start, tt.event_end AS ticket_event_end
FROM ticket_types tt
JOIN events e ON e.id = tt.event_id
WHERE tt.id = ANY($1::uuid[])
`

type ListTicketTypeDisplaysByIDsRow struct {
	ID               uuid.UUID
	Name             string
	EventName        string
	EventSlug        string
	EventVenue       string
	EventAddress     string
	EventStartDate   time.Time
	EventEndDate     time.Time
	TicketEventStart time.Time
	TicketEventEnd   time.Time
}

// Both tables belong to this domain, so the JOIN stays inside the boundary the
// order domain is not allowed to cross itself.
// event_start_date/event_end_date are the EVENT's dates; ticket_event_start/
// ticket_event_end are this ticket type's own admission window (spec 015). Both
// pairs travel together because the order page names the event AND each line's
// own day, and they are not interchangeable.
func (q *Queries) ListTicketTypeDisplaysByIDs(ctx context.Context, ids []uuid.UUID) ([]ListTicketTypeDisplaysByIDsRow, error) {
	rows, err := q.db.Query(ctx, listTicketTypeDisplaysByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketTypeDisplaysByIDsRow{}
	for rows.Next() {
		var i ListTicketTypeDisplaysByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventName,
			&i.EventSlug,
			&i.EventVenue,
			&i.EventAddress,
			&i.EventStartDate,
			&i.EventEndDate,
			&i.TicketEventStart,
			&i.TicketEventEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypeIDsByEventID = `-- name: ListTicketTypeIDsByEventID :many
SELECT id FROM ticket_types WHERE event_id = $1
`

func (q *Queries) ListTicketTypeIDsByEventID(ctx context.Context, eventID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTicketTypeIDsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypeNamesByIDs = `-- name: ListTicketTypeNamesByIDs :many
SELECT id, name FROM ticket_types WHERE id = ANY($1::uuid[])
`

type ListTicketTypeNamesByIDsRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListTicketTypeNamesByIDs(ctx context.Context, ids []uuid.UUID) ([]ListTicketTypeNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listTicketTypeNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketTypeNamesByIDsRow{}
	for rows.Next() {
		var i ListTicketTypeNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypeQuotasByIDs = `-- name: ListTicketTypeQuotasByIDs :many
SELECT id, name, quota FROM ticket_types WHERE id = ANY($1::uuid[])
`

type ListTicketTypeQuotasByIDsRow struct {
	ID    uuid.UUID
	Name  string
	Quota int32
}

// Remaining quota per ticket type. `quota` is the REMAINING counter (constitution,
// Critical Data Flow Rules), not the original allocation.
//
// The payment domain reads this to size the shortfall when a redelivered
// notification cannot settle an expired order (FR-019c), and to show an operator
// what an order holds against what is left before they request a resend
// (FR-022e). It is deliberately NOT the sold-count shown on the ticket-type
// editor, which counts released orders and so overstates what has been sold.
func (q *Queries) ListTicketTypeQuotasByIDs(ctx context.Context, ids []uuid.UUID) ([]ListTicketTypeQuotasByIDsRow, error) {
	rows, err := q.db.Query(ctx, listTicketTypeQuotasByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketTypeQuotasByIDsRow{}
	for rows.Next() {
		var i ListTicketTypeQuotasByIDsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Quota); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypesAdmin = `-- name: ListTicketTypesAdmin :many

SELECT id, event_id, name, description, price, quota, sales_start, sales_end, event_start, event_end, created_at, updated_at
FROM ticket_types
WHERE event_id = $1
ORDER BY created_at ASC
`

type ListTicketTypesAdminRow struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Name        string
	Description *string
	Price       decimal.Decimal
	Quota       int32
	SalesStart  time.Time
	SalesEnd    time.Time
	EventStart  time.Time
	EventEnd    time.Time
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

// Admin ticket-type CRUD ---------------------------------------------------
func (q *Queries) ListTicketTypesAdmin(ctx context.Context, eventID uuid.UUID) ([]ListTicketTypesAdminRow, error) {
	rows, err := q.db.Query(ctx, listTicketTypesAdmin, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketTypesAdminRow{}
	for rows.Next() {
		var i ListTicketTypesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Quota,
			&i.SalesStart,
			&i.SalesEnd,
			&i.EventStart,
			&i.EventEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypesByEventID = `-- name: ListTicketTypesByEventID :many
SELECT id, event_id, name, description, price, quota, sales_start, sales_end, event_start, event_end
FROM ticket_types
WHERE event_id = $1
ORDER BY price ASC, name ASC
`

type ListTicketTypesByEventIDRow struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Name        string
	Description *string
	Price       decimal.Decimal
	Quota       int32
	SalesStart  time.Time
	SalesEnd    time.Time
	EventStart  time.Time
	EventEnd    time.Time
}

func (q *Queries) ListTicketTypesByEventID(ctx context.Context, eventID uuid.UUID) ([]ListTicketTypesByEventIDRow, error) {
	rows, err := q.db.Query(ctx, listTicketTypesByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketTypesByEventIDRow{}
	for rows.Next() {
		var i ListTicketTypesByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Quota,
			&i.SalesStart,
			&i.SalesEnd,
			&i.EventStart,
			&i.EventEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const packageForCheckout = `-- name: PackageForCheckout :one
SELECT id, event_id, name, price, sales_start, sales_end, is_active
FROM packages
WHERE id = $1
`

type PackageForCheckoutRow struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	Name       string
	Price      decimal.Decimal
	SalesStart time.Time
	SalesEnd   time.Time
	IsActive   bool
}

// Server-side truth for a package at checkout: authoritative price, window, status
// and owning event. Composition is read separately via
// ListPackageComponentsByPackageIDs so both callers share one query.
func (q *Queries) PackageForCheckout(ctx context.Context, id uuid.UUID) (PackageForCheckoutRow, error) {
	row := q.db.QueryRow(ctx, packageForCheckout, id)
	var i PackageForCheckoutRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.SalesStart,
		&i.SalesEnd,
		&i.IsActive,
	)
	return i, err
}

const restoreQuota = `-- name: RestoreQuota :one
UPDATE ticket_types
SET quota = quota + $1, updated_at = now()
WHERE id = $2
RETURNING quota
`

type RestoreQuotaParams struct {
	Qty int32
	ID  uuid.UUID
}

func (q *Queries) RestoreQuota(ctx context.Context, arg RestoreQuotaParams) (int32, error) {
	row := q.db.QueryRow(ctx, restoreQuota, arg.Qty, arg.ID)
	var quota int32
	err := row.Scan(&quota)
	return quota, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET name = $2, slug = $3, description = $4, venue = $5, address = $6,
    start_date = $7, end_date = $8, banner_url = $9, status = $10, scale = $11, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, description, venue, address, start_date, end_date, banner_url, status, created_at, updated_at, scale
`

type UpdateEventParams struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description *string
	Venue       string
	Address     string
	StartDate   time.Time
	EndDate     time.Time
	BannerUrl   *string
	Status      string
	Scale       *int64
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Venue,
		arg.Address,
		arg.StartDate,
		arg.EndDate,
		arg.BannerUrl,
		arg.Status,
		arg.Scale,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.Address,
		&i.StartDate,
		&i.EndDate,
		&i.BannerUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scale,
	)
	return i, err
}

const updateEventActivity = `-- name: UpdateEventActivity :execrows
UPDATE event_activities
SET title = $3, description = $4, icon = $5, position = $6, updated_at = now()
WHERE id = $1 AND event_id = $2
`

type UpdateEventActivityParams struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Title       string
	Description string
	Icon        *string
	Position    int32
}

func (q *Queries) UpdateEventActivity(ctx context.Context, arg UpdateEventActivityParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventActivity,
		arg.ID,
		arg.EventID,
		arg.Title,
		arg.Description,
		arg.Icon,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEventGuestStar = `-- name: UpdateEventGuestStar :execrows
UPDATE event_guest_stars
SET name = $3, position = $4, updated_at = now()
WHERE id = $1 AND event_id = $2
`

type UpdateEventGuestStarParams struct {
	ID       uuid.UUID
	EventID  uuid.UUID
	Name     string
	Position int32
}

func (q *Queries) UpdateEventGuestStar(ctx context.Context, arg UpdateEventGuestStarParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventGuestStar,
		arg.ID,
		arg.EventID,
		arg.Name,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEventGuideline = `-- name: UpdateEventGuideline :execrows
UPDATE event_guidelines
SET description = $3, icon = $4, position = $5, updated_at = now()
WHERE id = $1 AND event_id = $2
`

type UpdateEventGuidelineParams struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Description string
	Icon        *string
	Position    int32
}

func (q *Queries) UpdateEventGuideline(ctx context.Context, arg UpdateEventGuidelineParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventGuideline,
		arg.ID,
		arg.EventID,
		arg.Description,
		arg.Icon,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePackage = `-- name: UpdatePackage :one
UPDATE packages
SET name = $2, description = $3, price = $4, sales_start = $5, sales_end = $6,
    is_active = $7, updated_at = now()
WHERE id = $1
RETURNING id, event_id, name, description, price, sales_start, sales_end, is_active,
          created_at, updated_at
`

type UpdatePackageParams struct {
	ID          uuid.UUID
	Name        string
	Description *string
	Price       decimal.Decimal
	SalesStart  time.Time
	SalesEnd    time.Time
	IsActive    bool
}

type UpdatePackageRow struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Name        string
	Description *string
	Price       decimal.Decimal
	SalesStart  time.Time
	SalesEnd    time.Time
	IsActive    bool
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

// event_id is absent on purpose: a package never moves between events, since its
// composition is bound to that event by the composite foreign keys.
func (q *Queries) UpdatePackage(ctx context.Context, arg UpdatePackageParams) (UpdatePackageRow, error) {
	row := q.db.QueryRow(ctx, updatePackage,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.SalesStart,
		arg.SalesEnd,
		arg.IsActive,
	)
	var i UpdatePackageRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.SalesStart,
		&i.SalesEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTicketType = `-- name: UpdateTicketType :one
UPDATE ticket_types
SET name = $2, description = $3, price = $4, quota = $5, sales_start = $6, sales_end = $7,
    event_start = $8, event_end = $9, updated_at = now()
WHERE id = $1
RETURNING id, event_id, name, description, price, quota, sales_start, sales_end, event_start, event_end, created_at, updated_at
`

type UpdateTicketTypeParams struct {
	ID          uuid.UUID
	Name        string
	Description *string
	Price       decimal.Decimal
	Quota       int32
	SalesStart  time.Time
	SalesEnd    time.Time
	EventStart  time.Time
	EventEnd    time.Time
}

type UpdateTicketTypeRow struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Name        string
	Description *string
	Price       decimal.Decimal
	Quota       int32
	SalesStart  time.Time
	SalesEnd    time.Time
	EventStart  time.Time
	EventEnd    time.Time
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

// `quota` is set ABSOLUTELY to the submitted remaining quota; past sales are never
// re-subtracted here (contracts/api.md, Admin Management).
func (q *Queries) UpdateTicketType(ctx context.Context, arg UpdateTicketTypeParams) (UpdateTicketTypeRow, error) {
	row := q.db.QueryRow(ctx, updateTicketType,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Quota,
		arg.SalesStart,
		arg.SalesEnd,
		arg.EventStart,
		arg.EventEnd,
	)
	var i UpdateTicketTypeRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quota,
		&i.SalesStart,
		&i.SalesEnd,
		&i.EventStart,
		&i.EventEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEventTerms = `-- name: UpsertEventTerms :one
INSERT INTO event_terms (event_id, content)
VALUES ($1, $2)
ON CONFLICT (event_id) DO UPDATE SET content = EXCLUDED.content, updated_at = now()
RETURNING id, event_id, content, created_at, updated_at
`

type UpsertEventTermsParams struct {
	EventID uuid.UUID
	Content string
}

// One live document per event (event_id UNIQUE): an edit overwrites in place.
func (q *Queries) UpsertEventTerms(ctx context.Context, arg UpsertEventTermsParams) (EventTerm, error) {
	row := q.db.QueryRow(ctx, upsertEventTerms, arg.EventID, arg.Content)
	var i EventTerm
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
