// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package eventsql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const checkAndDeductQuota = `-- name: CheckAndDeductQuota :one

UPDATE ticket_types
SET quota = quota - $1, updated_at = now()
WHERE id = $2 AND quota >= $1
RETURNING quota
`

type CheckAndDeductQuotaParams struct {
	Qty int32
	ID  uuid.UUID
}

// Quota mutation (EventProvider) -------------------------------------------
// `quota` is the REMAINING quota (constitution, Critical Data Flow Rules): the live
// counter checkout decrements and cancel/expire/deny/failure restore. The guarded
// WHERE makes the deduction atomic under concurrency — zero rows affected means
// insufficient quota, never a negative value.
func (q *Queries) CheckAndDeductQuota(ctx context.Context, arg CheckAndDeductQuotaParams) (int32, error) {
	row := q.db.QueryRow(ctx, checkAndDeductQuota, arg.Qty, arg.ID)
	var quota int32
	err := row.Scan(&quota)
	return quota, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (name, slug, description, venue, address, start_date, end_date, banner_url, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, slug, description, venue, address, start_date, end_date, banner_url, status, created_at, updated_at
`

type CreateEventParams struct {
	Name        string
	Slug        string
	Description *string
	Venue       string
	Address     string
	StartDate   time.Time
	EndDate     time.Time
	BannerUrl   *string
	Status      string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Venue,
		arg.Address,
		arg.StartDate,
		arg.EndDate,
		arg.BannerUrl,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.Address,
		&i.StartDate,
		&i.EndDate,
		&i.BannerUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicketType = `-- name: CreateTicketType :one
INSERT INTO ticket_types (event_id, name, price, quota, sales_start, sales_end)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_id, name, price, quota, sales_start, sales_end, created_at, updated_at
`

type CreateTicketTypeParams struct {
	EventID    uuid.UUID
	Name       string
	Price      decimal.Decimal
	Quota      int32
	SalesStart time.Time
	SalesEnd   time.Time
}

func (q *Queries) CreateTicketType(ctx context.Context, arg CreateTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, createTicketType,
		arg.EventID,
		arg.Name,
		arg.Price,
		arg.Quota,
		arg.SalesStart,
		arg.SalesEnd,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.Quota,
		&i.SalesStart,
		&i.SalesEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :execrows
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTicketType = `-- name: DeleteTicketType :execrows
DELETE FROM ticket_types WHERE id = $1
`

func (q *Queries) DeleteTicketType(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTicketType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTicketTypesByEventID = `-- name: DeleteTicketTypesByEventID :execrows
DELETE FROM ticket_types WHERE event_id = $1
`

func (q *Queries) DeleteTicketTypesByEventID(ctx context.Context, eventID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTicketTypesByEventID, eventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, name, slug, description, venue, address, start_date, end_date, banner_url, status, created_at, updated_at
FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.Address,
		&i.StartDate,
		&i.EndDate,
		&i.BannerUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedEventBySlug = `-- name: GetPublishedEventBySlug :one
SELECT id, name, slug, description, venue, address, start_date, end_date, banner_url, status
FROM events
WHERE slug = $1 AND status = 'PUBLISHED'
`

type GetPublishedEventBySlugRow struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description *string
	Venue       string
	Address     string
	StartDate   time.Time
	EndDate     time.Time
	BannerUrl   *string
	Status      string
}

func (q *Queries) GetPublishedEventBySlug(ctx context.Context, slug string) (GetPublishedEventBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublishedEventBySlug, slug)
	var i GetPublishedEventBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.Address,
		&i.StartDate,
		&i.EndDate,
		&i.BannerUrl,
		&i.Status,
	)
	return i, err
}

const getTicketTypeAdmin = `-- name: GetTicketTypeAdmin :one
SELECT id, event_id, name, price, quota, sales_start, sales_end, created_at, updated_at
FROM ticket_types
WHERE id = $1
`

func (q *Queries) GetTicketTypeAdmin(ctx context.Context, id uuid.UUID) (TicketType, error) {
	row := q.db.QueryRow(ctx, getTicketTypeAdmin, id)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.Quota,
		&i.SalesStart,
		&i.SalesEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketTypeByID = `-- name: GetTicketTypeByID :one
SELECT id, event_id, name, price, quota, sales_start, sales_end
FROM ticket_types
WHERE id = $1
`

type GetTicketTypeByIDRow struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	Name       string
	Price      decimal.Decimal
	Quota      int32
	SalesStart time.Time
	SalesEnd   time.Time
}

func (q *Queries) GetTicketTypeByID(ctx context.Context, id uuid.UUID) (GetTicketTypeByIDRow, error) {
	row := q.db.QueryRow(ctx, getTicketTypeByID, id)
	var i GetTicketTypeByIDRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.Quota,
		&i.SalesStart,
		&i.SalesEnd,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many

SELECT id, name, slug, description, venue, address, start_date, end_date, banner_url, status, created_at, updated_at
FROM events
ORDER BY start_date DESC
`

// Admin event CRUD ---------------------------------------------------------
func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Venue,
			&i.Address,
			&i.StartDate,
			&i.EndDate,
			&i.BannerUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEvents = `-- name: ListPublishedEvents :many

SELECT id, name, slug, description, venue, address, start_date, end_date, banner_url, status
FROM events
WHERE status = 'PUBLISHED'
ORDER BY start_date ASC
`

type ListPublishedEventsRow struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description *string
	Venue       string
	Address     string
	StartDate   time.Time
	EndDate     time.Time
	BannerUrl   *string
	Status      string
}

// Guest-facing reads -------------------------------------------------------
func (q *Queries) ListPublishedEvents(ctx context.Context) ([]ListPublishedEventsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedEventsRow{}
	for rows.Next() {
		var i ListPublishedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Venue,
			&i.Address,
			&i.StartDate,
			&i.EndDate,
			&i.BannerUrl,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypeIDsByEventID = `-- name: ListTicketTypeIDsByEventID :many
SELECT id FROM ticket_types WHERE event_id = $1
`

func (q *Queries) ListTicketTypeIDsByEventID(ctx context.Context, eventID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTicketTypeIDsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypeNamesByIDs = `-- name: ListTicketTypeNamesByIDs :many
SELECT id, name FROM ticket_types WHERE id = ANY($1::uuid[])
`

type ListTicketTypeNamesByIDsRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListTicketTypeNamesByIDs(ctx context.Context, ids []uuid.UUID) ([]ListTicketTypeNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listTicketTypeNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketTypeNamesByIDsRow{}
	for rows.Next() {
		var i ListTicketTypeNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypesAdmin = `-- name: ListTicketTypesAdmin :many

SELECT id, event_id, name, price, quota, sales_start, sales_end, created_at, updated_at
FROM ticket_types
WHERE event_id = $1
ORDER BY created_at ASC
`

// Admin ticket-type CRUD ---------------------------------------------------
func (q *Queries) ListTicketTypesAdmin(ctx context.Context, eventID uuid.UUID) ([]TicketType, error) {
	rows, err := q.db.Query(ctx, listTicketTypesAdmin, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketType{}
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Price,
			&i.Quota,
			&i.SalesStart,
			&i.SalesEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypesByEventID = `-- name: ListTicketTypesByEventID :many
SELECT id, event_id, name, price, quota, sales_start, sales_end
FROM ticket_types
WHERE event_id = $1
ORDER BY price ASC, name ASC
`

type ListTicketTypesByEventIDRow struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	Name       string
	Price      decimal.Decimal
	Quota      int32
	SalesStart time.Time
	SalesEnd   time.Time
}

func (q *Queries) ListTicketTypesByEventID(ctx context.Context, eventID uuid.UUID) ([]ListTicketTypesByEventIDRow, error) {
	rows, err := q.db.Query(ctx, listTicketTypesByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketTypesByEventIDRow{}
	for rows.Next() {
		var i ListTicketTypesByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Price,
			&i.Quota,
			&i.SalesStart,
			&i.SalesEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreQuota = `-- name: RestoreQuota :one
UPDATE ticket_types
SET quota = quota + $1, updated_at = now()
WHERE id = $2
RETURNING quota
`

type RestoreQuotaParams struct {
	Qty int32
	ID  uuid.UUID
}

func (q *Queries) RestoreQuota(ctx context.Context, arg RestoreQuotaParams) (int32, error) {
	row := q.db.QueryRow(ctx, restoreQuota, arg.Qty, arg.ID)
	var quota int32
	err := row.Scan(&quota)
	return quota, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET name = $2, slug = $3, description = $4, venue = $5, address = $6,
    start_date = $7, end_date = $8, banner_url = $9, status = $10, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, description, venue, address, start_date, end_date, banner_url, status, created_at, updated_at
`

type UpdateEventParams struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description *string
	Venue       string
	Address     string
	StartDate   time.Time
	EndDate     time.Time
	BannerUrl   *string
	Status      string
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Venue,
		arg.Address,
		arg.StartDate,
		arg.EndDate,
		arg.BannerUrl,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Venue,
		&i.Address,
		&i.StartDate,
		&i.EndDate,
		&i.BannerUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTicketType = `-- name: UpdateTicketType :one
UPDATE ticket_types
SET name = $2, price = $3, quota = $4, sales_start = $5, sales_end = $6, updated_at = now()
WHERE id = $1
RETURNING id, event_id, name, price, quota, sales_start, sales_end, created_at, updated_at
`

type UpdateTicketTypeParams struct {
	ID         uuid.UUID
	Name       string
	Price      decimal.Decimal
	Quota      int32
	SalesStart time.Time
	SalesEnd   time.Time
}

// `quota` is set ABSOLUTELY to the submitted remaining quota; past sales are never
// re-subtracted here (contracts/api.md, Admin Management).
func (q *Queries) UpdateTicketType(ctx context.Context, arg UpdateTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, updateTicketType,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Quota,
		arg.SalesStart,
		arg.SalesEnd,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.Quota,
		&i.SalesStart,
		&i.SalesEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
