// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eventsql

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Event struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description *string
	Venue       string
	Address     string
	StartDate   time.Time
	EndDate     time.Time
	BannerUrl   *string
	Status      string
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

type TicketType struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	Name       string
	Price      decimal.Decimal
	Quota      int32
	SalesStart time.Time
	SalesEnd   time.Time
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
}
