// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eventsql

import (
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description *string
	Venue       string
	Address     string
	StartDate   time.Time
	EndDate     time.Time
	BannerUrl   *string
	Status      string
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
	Scale       *int64
}

type EventActivity struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Title       string
	Description string
	Icon        *string
	Position    int32
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

type EventGuestStar struct {
	ID        uuid.UUID
	EventID   uuid.UUID
	Name      string
	Position  int32
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

type EventGuideline struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	Description string
	Icon        *string
	Position    int32
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

type EventTerm struct {
	ID        uuid.UUID
	EventID   uuid.UUID
	Content   string
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

type PackageTicket struct {
	ID           uuid.UUID
	PackageID    uuid.UUID
	TicketTypeID uuid.UUID
	EventID      uuid.UUID
	Quantity     int32
	CreatedAt    *time.Time
}
